//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3615
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nsPuls3060.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("31")]
        public int BetalingsFristiDageGamleMedlemmer {
            get {
                return ((int)(this["BetalingsFristiDageGamleMedlemmer"]));
            }
            set {
                this["BetalingsFristiDageGamleMedlemmer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("61")]
        public int BetalingsFristiDageNyeMedlemmer {
            get {
                return ((int)(this["BetalingsFristiDageNyeMedlemmer"]));
            }
            set {
                this["BetalingsFristiDageNyeMedlemmer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Documents and Settings\\mha\\Dokumenter\\Medlem3060\\Databaser\\SQLCompact\\dbDataTr" +
            "ansSumma.sdf")]
        public string DataBasePath {
            get {
                return ((string)(this["DataBasePath"]));
            }
            set {
                this["DataBasePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100, 100")]
        public global::System.Drawing.Point frmMainPoint {
            get {
                return ((global::System.Drawing.Point)(this["frmMainPoint"]));
            }
            set {
                this["frmMainPoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1024, 800")]
        public global::System.Drawing.Size frmMainSize {
            get {
                return ((global::System.Drawing.Size)(this["frmMainSize"]));
            }
            set {
                this["frmMainSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100, 100")]
        public global::System.Drawing.Point frmMedlemmerPoint {
            get {
                return ((global::System.Drawing.Point)(this["frmMedlemmerPoint"]));
            }
            set {
                this["frmMedlemmerPoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("800, 600")]
        public global::System.Drawing.Size frmMedlemmerSize {
            get {
                return ((global::System.Drawing.Size)(this["frmMedlemmerSize"]));
            }
            set {
                this["frmMedlemmerSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10, 10")]
        public global::System.Drawing.Point frmKreditorPoint {
            get {
                return ((global::System.Drawing.Point)(this["frmKreditorPoint"]));
            }
            set {
                this["frmKreditorPoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("304, 300")]
        public global::System.Drawing.Size frmKreditorSize {
            get {
                return ((global::System.Drawing.Size)(this["frmKreditorSize"]));
            }
            set {
                this["frmKreditorSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState frmKreditorState {
            get {
                return ((global::System.Windows.Forms.FormWindowState)(this["frmKreditorState"]));
            }
            set {
                this["frmKreditorState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState frmRegnskabState {
            get {
                return ((global::System.Windows.Forms.FormWindowState)(this["frmRegnskabState"]));
            }
            set {
                this["frmRegnskabState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("531, 398")]
        public global::System.Drawing.Size frmRegnskabSize {
            get {
                return ((global::System.Drawing.Size)(this["frmRegnskabSize"]));
            }
            set {
                this["frmRegnskabSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point frmRegnskabPoint {
            get {
                return ((global::System.Drawing.Point)(this["frmRegnskabPoint"]));
            }
            set {
                this["frmRegnskabPoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("829, 513")]
        public global::System.Drawing.Size frmKontingentForslagSize {
            get {
                return ((global::System.Drawing.Size)(this["frmKontingentForslagSize"]));
            }
            set {
                this["frmKontingentForslagSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point frmKontingentForslagPoint {
            get {
                return ((global::System.Drawing.Point)(this["frmKontingentForslagPoint"]));
            }
            set {
                this["frmKontingentForslagPoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("280")]
        public int frmMedlemmerSplitteDist {
            get {
                return ((int)(this["frmMedlemmerSplitteDist"]));
            }
            set {
                this["frmMedlemmerSplitteDist"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point frmPbsfilesPoint {
            get {
                return ((global::System.Drawing.Point)(this["frmPbsfilesPoint"]));
            }
            set {
                this["frmPbsfilesPoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("707, 511")]
        public global::System.Drawing.Size frmPbsfilesSize {
            get {
                return ((global::System.Drawing.Size)(this["frmPbsfilesSize"]));
            }
            set {
                this["frmPbsfilesSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("800, 600")]
        public global::System.Drawing.Size FrmBetalingsForslagSize {
            get {
                return ((global::System.Drawing.Size)(this["FrmBetalingsForslagSize"]));
            }
            set {
                this["FrmBetalingsForslagSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point FrmBetalingsForslagPoint {
            get {
                return ((global::System.Drawing.Point)(this["FrmBetalingsForslagPoint"]));
            }
            set {
                this["FrmBetalingsForslagPoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("829, 513")]
        public global::System.Drawing.Size frmRykkerForslagClientSize {
            get {
                return ((global::System.Drawing.Size)(this["frmRykkerForslagClientSize"]));
            }
            set {
                this["frmRykkerForslagClientSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point frmRykkerForslagPoint {
            get {
                return ((global::System.Drawing.Point)(this["frmRykkerForslagPoint"]));
            }
            set {
                this["frmRykkerForslagPoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("416, 211")]
        public global::System.Drawing.Size frmPbsnetdirSize {
            get {
                return ((global::System.Drawing.Size)(this["frmPbsnetdirSize"]));
            }
            set {
                this["frmPbsnetdirSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100, 100")]
        public global::System.Drawing.Point frmPbsnetdirPoint {
            get {
                return ((global::System.Drawing.Point)(this["frmPbsnetdirPoint"]));
            }
            set {
                this["frmPbsnetdirPoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("274")]
        public int BankafstemningSplitterDistancr {
            get {
                return ((int)(this["BankafstemningSplitterDistancr"]));
            }
            set {
                this["BankafstemningSplitterDistancr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("829, 389")]
        public global::System.Drawing.Size BankafstemningSize {
            get {
                return ((global::System.Drawing.Size)(this["BankafstemningSize"]));
            }
            set {
                this["BankafstemningSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point FrmBankkontoudtogLocation {
            get {
                return ((global::System.Drawing.Point)(this["FrmBankkontoudtogLocation"]));
            }
            set {
                this["FrmBankkontoudtogLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("393, 416")]
        public global::System.Drawing.Size frmBankkontoudtogSize {
            get {
                return ((global::System.Drawing.Size)(this["frmBankkontoudtogSize"]));
            }
            set {
                this["frmBankkontoudtogSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point frmKladderLocation {
            get {
                return ((global::System.Drawing.Point)(this["frmKladderLocation"]));
            }
            set {
                this["frmKladderLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("530, 259")]
        public global::System.Drawing.Size frmKladderSize {
            get {
                return ((global::System.Drawing.Size)(this["frmKladderSize"]));
            }
            set {
                this["frmKladderSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point frmNyeKladderLocation {
            get {
                return ((global::System.Drawing.Point)(this["frmNyeKladderLocation"]));
            }
            set {
                this["frmNyeKladderLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("521, 259")]
        public global::System.Drawing.Size frmNyeKladderSize {
            get {
                return ((global::System.Drawing.Size)(this["frmNyeKladderSize"]));
            }
            set {
                this["frmNyeKladderSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point frmBilagLoacation {
            get {
                return ((global::System.Drawing.Point)(this["frmBilagLoacation"]));
            }
            set {
                this["frmBilagLoacation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("870, 346")]
        public global::System.Drawing.Size frmBilagSize {
            get {
                return ((global::System.Drawing.Size)(this["frmBilagSize"]));
            }
            set {
                this["frmBilagSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("246")]
        public int frmBilagSplitDistance {
            get {
                return ((int)(this["frmBilagSplitDistance"]));
            }
            set {
                this["frmBilagSplitDistance"] = value;
            }
        }
    }
}
