#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nsPbs3060
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="puls3061_dk_db")]
	public partial class dbData3060DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttblsftp(tblsftp instance);
    partial void Updatetblsftp(tblsftp instance);
    partial void Deletetblsftp(tblsftp instance);
    partial void Inserttblpbsfile(tblpbsfile instance);
    partial void Updatetblpbsfile(tblpbsfile instance);
    partial void Deletetblpbsfile(tblpbsfile instance);
    partial void Inserttblpbsfilename(tblpbsfilename instance);
    partial void Updatetblpbsfilename(tblpbsfilename instance);
    partial void Deletetblpbsfilename(tblpbsfilename instance);
    partial void Inserttblpbsforsendelse(tblpbsforsendelse instance);
    partial void Updatetblpbsforsendelse(tblpbsforsendelse instance);
    partial void Deletetblpbsforsendelse(tblpbsforsendelse instance);
    partial void Inserttbltilpb(tbltilpb instance);
    partial void Updatetbltilpb(tbltilpb instance);
    partial void Deletetbltilpb(tbltilpb instance);
    #endregion
		
		public dbData3060DataContext() : 
				base(global::nsPbs3060.Properties.Settings.Default.puls3061_dk_dbConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dbData3060DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbData3060DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbData3060DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbData3060DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tblsftp> tblsftps
		{
			get
			{
				return this.GetTable<tblsftp>();
			}
		}
		
		public System.Data.Linq.Table<tblpbsfile> tblpbsfiles
		{
			get
			{
				return this.GetTable<tblpbsfile>();
			}
		}
		
		public System.Data.Linq.Table<tblpbsfilename> tblpbsfilenames
		{
			get
			{
				return this.GetTable<tblpbsfilename>();
			}
		}
		
		public System.Data.Linq.Table<tblpbsforsendelse> tblpbsforsendelses
		{
			get
			{
				return this.GetTable<tblpbsforsendelse>();
			}
		}
		
		public System.Data.Linq.Table<tbltilpb> tbltilpbs
		{
			get
			{
				return this.GetTable<tbltilpb>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetSysinfo", IsComposable=true)]
		public string GetSysinfo([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Pvkey", DbType="NVarChar(10)")] string pvkey)
		{
			return ((string)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pvkey).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.nextval")]
		public int nextval([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Pnrserienavn", DbType="NVarChar(30)")] string pnrserienavn)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pnrserienavn);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblsftp")]
	public partial class tblsftp : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _navn;
		
		private string _host;
		
		private string _port;
		
		private string _user;
		
		private string _outbound;
		
		private string _inbound;
		
		private string _pincode;
		
		private string _certificate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnavnChanging(string value);
    partial void OnnavnChanged();
    partial void OnhostChanging(string value);
    partial void OnhostChanged();
    partial void OnportChanging(string value);
    partial void OnportChanged();
    partial void OnuserChanging(string value);
    partial void OnuserChanged();
    partial void OnoutboundChanging(string value);
    partial void OnoutboundChanged();
    partial void OninboundChanging(string value);
    partial void OninboundChanged();
    partial void OnpincodeChanging(string value);
    partial void OnpincodeChanged();
    partial void OncertificateChanging(string value);
    partial void OncertificateChanged();
    #endregion
		
		public tblsftp()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_navn", DbType="NVarChar(64) NOT NULL", CanBeNull=false)]
		public string navn
		{
			get
			{
				return this._navn;
			}
			set
			{
				if ((this._navn != value))
				{
					this.OnnavnChanging(value);
					this.SendPropertyChanging();
					this._navn = value;
					this.SendPropertyChanged("navn");
					this.OnnavnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_host", DbType="NVarChar(64) NOT NULL", CanBeNull=false)]
		public string host
		{
			get
			{
				return this._host;
			}
			set
			{
				if ((this._host != value))
				{
					this.OnhostChanging(value);
					this.SendPropertyChanging();
					this._host = value;
					this.SendPropertyChanged("host");
					this.OnhostChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_port", DbType="NVarChar(5) NOT NULL", CanBeNull=false)]
		public string port
		{
			get
			{
				return this._port;
			}
			set
			{
				if ((this._port != value))
				{
					this.OnportChanging(value);
					this.SendPropertyChanging();
					this._port = value;
					this.SendPropertyChanged("port");
					this.OnportChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[user]", Storage="_user", DbType="NVarChar(16) NOT NULL", CanBeNull=false)]
		public string user
		{
			get
			{
				return this._user;
			}
			set
			{
				if ((this._user != value))
				{
					this.OnuserChanging(value);
					this.SendPropertyChanging();
					this._user = value;
					this.SendPropertyChanged("user");
					this.OnuserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_outbound", DbType="NVarChar(64)")]
		public string outbound
		{
			get
			{
				return this._outbound;
			}
			set
			{
				if ((this._outbound != value))
				{
					this.OnoutboundChanging(value);
					this.SendPropertyChanging();
					this._outbound = value;
					this.SendPropertyChanged("outbound");
					this.OnoutboundChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_inbound", DbType="NVarChar(64)")]
		public string inbound
		{
			get
			{
				return this._inbound;
			}
			set
			{
				if ((this._inbound != value))
				{
					this.OninboundChanging(value);
					this.SendPropertyChanging();
					this._inbound = value;
					this.SendPropertyChanged("inbound");
					this.OninboundChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pincode", DbType="NVarChar(64)")]
		public string pincode
		{
			get
			{
				return this._pincode;
			}
			set
			{
				if ((this._pincode != value))
				{
					this.OnpincodeChanging(value);
					this.SendPropertyChanging();
					this._pincode = value;
					this.SendPropertyChanged("pincode");
					this.OnpincodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_certificate", DbType="NVarChar(4000)")]
		public string certificate
		{
			get
			{
				return this._certificate;
			}
			set
			{
				if ((this._certificate != value))
				{
					this.OncertificateChanging(value);
					this.SendPropertyChanging();
					this._certificate = value;
					this.SendPropertyChanged("certificate");
					this.OncertificateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblpbsfile")]
	public partial class tblpbsfile : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _pbsfilesid;
		
		private int _seqnr;
		
		private string _data;
		
		private EntityRef<tblpbsfilename> _tblpbsfilename;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnpbsfilesidChanging(int value);
    partial void OnpbsfilesidChanged();
    partial void OnseqnrChanging(int value);
    partial void OnseqnrChanged();
    partial void OndataChanging(string value);
    partial void OndataChanged();
    #endregion
		
		public tblpbsfile()
		{
			this._tblpbsfilename = default(EntityRef<tblpbsfilename>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pbsfilesid", DbType="Int NOT NULL")]
		public int pbsfilesid
		{
			get
			{
				return this._pbsfilesid;
			}
			set
			{
				if ((this._pbsfilesid != value))
				{
					if (this._tblpbsfilename.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnpbsfilesidChanging(value);
					this.SendPropertyChanging();
					this._pbsfilesid = value;
					this.SendPropertyChanged("pbsfilesid");
					this.OnpbsfilesidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_seqnr", DbType="Int NOT NULL")]
		public int seqnr
		{
			get
			{
				return this._seqnr;
			}
			set
			{
				if ((this._seqnr != value))
				{
					this.OnseqnrChanging(value);
					this.SendPropertyChanging();
					this._seqnr = value;
					this.SendPropertyChanged("seqnr");
					this.OnseqnrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data", DbType="NVarChar(128)")]
		public string data
		{
			get
			{
				return this._data;
			}
			set
			{
				if ((this._data != value))
				{
					this.OndataChanging(value);
					this.SendPropertyChanging();
					this._data = value;
					this.SendPropertyChanged("data");
					this.OndataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblpbsfilename_tblpbsfile", Storage="_tblpbsfilename", ThisKey="pbsfilesid", OtherKey="id", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public tblpbsfilename tblpbsfilename
		{
			get
			{
				return this._tblpbsfilename.Entity;
			}
			set
			{
				tblpbsfilename previousValue = this._tblpbsfilename.Entity;
				if (((previousValue != value) 
							|| (this._tblpbsfilename.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblpbsfilename.Entity = null;
						previousValue.tblpbsfiles.Remove(this);
					}
					this._tblpbsfilename.Entity = value;
					if ((value != null))
					{
						value.tblpbsfiles.Add(this);
						this._pbsfilesid = value.id;
					}
					else
					{
						this._pbsfilesid = default(int);
					}
					this.SendPropertyChanged("tblpbsfilename");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblpbsfilename")]
	public partial class tblpbsfilename : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _type;
		
		private string _path;
		
		private string _filename;
		
		private System.Nullable<int> _size;
		
		private System.Nullable<System.DateTime> _atime;
		
		private System.Nullable<System.DateTime> _mtime;
		
		private string _perm;
		
		private System.Nullable<int> _uid;
		
		private System.Nullable<int> _gid;
		
		private System.Nullable<System.DateTime> _transmittime;
		
		private System.Nullable<int> _pbsforsendelseid;
		
		private EntitySet<tblpbsfile> _tblpbsfiles;
		
		private EntityRef<tblpbsforsendelse> _tblpbsforsendelse;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OntypeChanging(System.Nullable<int> value);
    partial void OntypeChanged();
    partial void OnpathChanging(string value);
    partial void OnpathChanged();
    partial void OnfilenameChanging(string value);
    partial void OnfilenameChanged();
    partial void OnsizeChanging(System.Nullable<int> value);
    partial void OnsizeChanged();
    partial void OnatimeChanging(System.Nullable<System.DateTime> value);
    partial void OnatimeChanged();
    partial void OnmtimeChanging(System.Nullable<System.DateTime> value);
    partial void OnmtimeChanged();
    partial void OnpermChanging(string value);
    partial void OnpermChanged();
    partial void OnuidChanging(System.Nullable<int> value);
    partial void OnuidChanged();
    partial void OngidChanging(System.Nullable<int> value);
    partial void OngidChanged();
    partial void OntransmittimeChanging(System.Nullable<System.DateTime> value);
    partial void OntransmittimeChanged();
    partial void OnpbsforsendelseidChanging(System.Nullable<int> value);
    partial void OnpbsforsendelseidChanged();
    #endregion
		
		public tblpbsfilename()
		{
			this._tblpbsfiles = new EntitySet<tblpbsfile>(new Action<tblpbsfile>(this.attach_tblpbsfiles), new Action<tblpbsfile>(this.detach_tblpbsfiles));
			this._tblpbsforsendelse = default(EntityRef<tblpbsforsendelse>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="Int")]
		public System.Nullable<int> type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this.OntypeChanging(value);
					this.SendPropertyChanging();
					this._type = value;
					this.SendPropertyChanged("type");
					this.OntypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_path", DbType="NVarChar(255)")]
		public string path
		{
			get
			{
				return this._path;
			}
			set
			{
				if ((this._path != value))
				{
					this.OnpathChanging(value);
					this.SendPropertyChanging();
					this._path = value;
					this.SendPropertyChanged("path");
					this.OnpathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_filename", DbType="NVarChar(50)")]
		public string filename
		{
			get
			{
				return this._filename;
			}
			set
			{
				if ((this._filename != value))
				{
					this.OnfilenameChanging(value);
					this.SendPropertyChanging();
					this._filename = value;
					this.SendPropertyChanged("filename");
					this.OnfilenameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_size", DbType="Int")]
		public System.Nullable<int> size
		{
			get
			{
				return this._size;
			}
			set
			{
				if ((this._size != value))
				{
					this.OnsizeChanging(value);
					this.SendPropertyChanging();
					this._size = value;
					this.SendPropertyChanged("size");
					this.OnsizeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_atime", DbType="DateTime")]
		public System.Nullable<System.DateTime> atime
		{
			get
			{
				return this._atime;
			}
			set
			{
				if ((this._atime != value))
				{
					this.OnatimeChanging(value);
					this.SendPropertyChanging();
					this._atime = value;
					this.SendPropertyChanged("atime");
					this.OnatimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mtime", DbType="DateTime")]
		public System.Nullable<System.DateTime> mtime
		{
			get
			{
				return this._mtime;
			}
			set
			{
				if ((this._mtime != value))
				{
					this.OnmtimeChanging(value);
					this.SendPropertyChanging();
					this._mtime = value;
					this.SendPropertyChanged("mtime");
					this.OnmtimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[perm]", Storage="_perm", DbType="NVarChar(50)")]
		public string perm
		{
			get
			{
				return this._perm;
			}
			set
			{
				if ((this._perm != value))
				{
					this.OnpermChanging(value);
					this.SendPropertyChanging();
					this._perm = value;
					this.SendPropertyChanged("perm");
					this.OnpermChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uid", DbType="Int")]
		public System.Nullable<int> uid
		{
			get
			{
				return this._uid;
			}
			set
			{
				if ((this._uid != value))
				{
					this.OnuidChanging(value);
					this.SendPropertyChanging();
					this._uid = value;
					this.SendPropertyChanged("uid");
					this.OnuidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gid", DbType="Int")]
		public System.Nullable<int> gid
		{
			get
			{
				return this._gid;
			}
			set
			{
				if ((this._gid != value))
				{
					this.OngidChanging(value);
					this.SendPropertyChanging();
					this._gid = value;
					this.SendPropertyChanged("gid");
					this.OngidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_transmittime", DbType="DateTime")]
		public System.Nullable<System.DateTime> transmittime
		{
			get
			{
				return this._transmittime;
			}
			set
			{
				if ((this._transmittime != value))
				{
					this.OntransmittimeChanging(value);
					this.SendPropertyChanging();
					this._transmittime = value;
					this.SendPropertyChanged("transmittime");
					this.OntransmittimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pbsforsendelseid", DbType="Int")]
		public System.Nullable<int> pbsforsendelseid
		{
			get
			{
				return this._pbsforsendelseid;
			}
			set
			{
				if ((this._pbsforsendelseid != value))
				{
					if (this._tblpbsforsendelse.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnpbsforsendelseidChanging(value);
					this.SendPropertyChanging();
					this._pbsforsendelseid = value;
					this.SendPropertyChanged("pbsforsendelseid");
					this.OnpbsforsendelseidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblpbsfilename_tblpbsfile", Storage="_tblpbsfiles", ThisKey="id", OtherKey="pbsfilesid")]
		public EntitySet<tblpbsfile> tblpbsfiles
		{
			get
			{
				return this._tblpbsfiles;
			}
			set
			{
				this._tblpbsfiles.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblpbsforsendelse_tblpbsfilename", Storage="_tblpbsforsendelse", ThisKey="pbsforsendelseid", OtherKey="id", IsForeignKey=true, DeleteRule="CASCADE")]
		public tblpbsforsendelse tblpbsforsendelse
		{
			get
			{
				return this._tblpbsforsendelse.Entity;
			}
			set
			{
				tblpbsforsendelse previousValue = this._tblpbsforsendelse.Entity;
				if (((previousValue != value) 
							|| (this._tblpbsforsendelse.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblpbsforsendelse.Entity = null;
						previousValue.tblpbsfilenames.Remove(this);
					}
					this._tblpbsforsendelse.Entity = value;
					if ((value != null))
					{
						value.tblpbsfilenames.Add(this);
						this._pbsforsendelseid = value.id;
					}
					else
					{
						this._pbsforsendelseid = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblpbsforsendelse");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblpbsfiles(tblpbsfile entity)
		{
			this.SendPropertyChanging();
			entity.tblpbsfilename = this;
		}
		
		private void detach_tblpbsfiles(tblpbsfile entity)
		{
			this.SendPropertyChanging();
			entity.tblpbsfilename = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblpbsforsendelse")]
	public partial class tblpbsforsendelse : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _delsystem;
		
		private string _leverancetype;
		
		private string _oprettetaf;
		
		private System.Nullable<System.DateTime> _oprettet;
		
		private System.Nullable<int> _leveranceid;
		
		private EntitySet<tblpbsfilename> _tblpbsfilenames;
		
		private EntitySet<tbltilpb> _tbltilpbs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OndelsystemChanging(string value);
    partial void OndelsystemChanged();
    partial void OnleverancetypeChanging(string value);
    partial void OnleverancetypeChanged();
    partial void OnoprettetafChanging(string value);
    partial void OnoprettetafChanged();
    partial void OnoprettetChanging(System.Nullable<System.DateTime> value);
    partial void OnoprettetChanged();
    partial void OnleveranceidChanging(System.Nullable<int> value);
    partial void OnleveranceidChanged();
    #endregion
		
		public tblpbsforsendelse()
		{
			this._tblpbsfilenames = new EntitySet<tblpbsfilename>(new Action<tblpbsfilename>(this.attach_tblpbsfilenames), new Action<tblpbsfilename>(this.detach_tblpbsfilenames));
			this._tbltilpbs = new EntitySet<tbltilpb>(new Action<tbltilpb>(this.attach_tbltilpbs), new Action<tbltilpb>(this.detach_tbltilpbs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_delsystem", DbType="NVarChar(3) NOT NULL", CanBeNull=false)]
		public string delsystem
		{
			get
			{
				return this._delsystem;
			}
			set
			{
				if ((this._delsystem != value))
				{
					this.OndelsystemChanging(value);
					this.SendPropertyChanging();
					this._delsystem = value;
					this.SendPropertyChanged("delsystem");
					this.OndelsystemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_leverancetype", DbType="NVarChar(4)")]
		public string leverancetype
		{
			get
			{
				return this._leverancetype;
			}
			set
			{
				if ((this._leverancetype != value))
				{
					this.OnleverancetypeChanging(value);
					this.SendPropertyChanging();
					this._leverancetype = value;
					this.SendPropertyChanged("leverancetype");
					this.OnleverancetypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_oprettetaf", DbType="NVarChar(3)")]
		public string oprettetaf
		{
			get
			{
				return this._oprettetaf;
			}
			set
			{
				if ((this._oprettetaf != value))
				{
					this.OnoprettetafChanging(value);
					this.SendPropertyChanging();
					this._oprettetaf = value;
					this.SendPropertyChanged("oprettetaf");
					this.OnoprettetafChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_oprettet", DbType="DateTime")]
		public System.Nullable<System.DateTime> oprettet
		{
			get
			{
				return this._oprettet;
			}
			set
			{
				if ((this._oprettet != value))
				{
					this.OnoprettetChanging(value);
					this.SendPropertyChanging();
					this._oprettet = value;
					this.SendPropertyChanged("oprettet");
					this.OnoprettetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_leveranceid", DbType="Int")]
		public System.Nullable<int> leveranceid
		{
			get
			{
				return this._leveranceid;
			}
			set
			{
				if ((this._leveranceid != value))
				{
					this.OnleveranceidChanging(value);
					this.SendPropertyChanging();
					this._leveranceid = value;
					this.SendPropertyChanged("leveranceid");
					this.OnleveranceidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblpbsforsendelse_tblpbsfilename", Storage="_tblpbsfilenames", ThisKey="id", OtherKey="pbsforsendelseid")]
		public EntitySet<tblpbsfilename> tblpbsfilenames
		{
			get
			{
				return this._tblpbsfilenames;
			}
			set
			{
				this._tblpbsfilenames.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblpbsforsendelse_tbltilpb", Storage="_tbltilpbs", ThisKey="id", OtherKey="pbsforsendelseid")]
		public EntitySet<tbltilpb> tbltilpbs
		{
			get
			{
				return this._tbltilpbs;
			}
			set
			{
				this._tbltilpbs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblpbsfilenames(tblpbsfilename entity)
		{
			this.SendPropertyChanging();
			entity.tblpbsforsendelse = this;
		}
		
		private void detach_tblpbsfilenames(tblpbsfilename entity)
		{
			this.SendPropertyChanging();
			entity.tblpbsforsendelse = null;
		}
		
		private void attach_tbltilpbs(tbltilpb entity)
		{
			this.SendPropertyChanging();
			entity.tblpbsforsendelse = this;
		}
		
		private void detach_tbltilpbs(tbltilpb entity)
		{
			this.SendPropertyChanging();
			entity.tblpbsforsendelse = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbltilpbs")]
	public partial class tbltilpb : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _delsystem;
		
		private string _leverancetype;
		
		private System.Nullable<System.DateTime> _bilagdato;
		
		private System.Nullable<int> _pbsforsendelseid;
		
		private System.Nullable<System.DateTime> _udtrukket;
		
		private string _leverancespecifikation;
		
		private System.Nullable<System.DateTime> _leverancedannelsesdato;
		
		private EntityRef<tblpbsforsendelse> _tblpbsforsendelse;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OndelsystemChanging(string value);
    partial void OndelsystemChanged();
    partial void OnleverancetypeChanging(string value);
    partial void OnleverancetypeChanged();
    partial void OnbilagdatoChanging(System.Nullable<System.DateTime> value);
    partial void OnbilagdatoChanged();
    partial void OnpbsforsendelseidChanging(System.Nullable<int> value);
    partial void OnpbsforsendelseidChanged();
    partial void OnudtrukketChanging(System.Nullable<System.DateTime> value);
    partial void OnudtrukketChanged();
    partial void OnleverancespecifikationChanging(string value);
    partial void OnleverancespecifikationChanged();
    partial void OnleverancedannelsesdatoChanging(System.Nullable<System.DateTime> value);
    partial void OnleverancedannelsesdatoChanged();
    #endregion
		
		public tbltilpb()
		{
			this._tblpbsforsendelse = default(EntityRef<tblpbsforsendelse>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_delsystem", DbType="NVarChar(3)")]
		public string delsystem
		{
			get
			{
				return this._delsystem;
			}
			set
			{
				if ((this._delsystem != value))
				{
					this.OndelsystemChanging(value);
					this.SendPropertyChanging();
					this._delsystem = value;
					this.SendPropertyChanged("delsystem");
					this.OndelsystemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_leverancetype", DbType="NVarChar(4)")]
		public string leverancetype
		{
			get
			{
				return this._leverancetype;
			}
			set
			{
				if ((this._leverancetype != value))
				{
					this.OnleverancetypeChanging(value);
					this.SendPropertyChanging();
					this._leverancetype = value;
					this.SendPropertyChanged("leverancetype");
					this.OnleverancetypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bilagdato", DbType="DateTime")]
		public System.Nullable<System.DateTime> bilagdato
		{
			get
			{
				return this._bilagdato;
			}
			set
			{
				if ((this._bilagdato != value))
				{
					this.OnbilagdatoChanging(value);
					this.SendPropertyChanging();
					this._bilagdato = value;
					this.SendPropertyChanged("bilagdato");
					this.OnbilagdatoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pbsforsendelseid", DbType="Int")]
		public System.Nullable<int> pbsforsendelseid
		{
			get
			{
				return this._pbsforsendelseid;
			}
			set
			{
				if ((this._pbsforsendelseid != value))
				{
					if (this._tblpbsforsendelse.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnpbsforsendelseidChanging(value);
					this.SendPropertyChanging();
					this._pbsforsendelseid = value;
					this.SendPropertyChanged("pbsforsendelseid");
					this.OnpbsforsendelseidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_udtrukket", DbType="DateTime")]
		public System.Nullable<System.DateTime> udtrukket
		{
			get
			{
				return this._udtrukket;
			}
			set
			{
				if ((this._udtrukket != value))
				{
					this.OnudtrukketChanging(value);
					this.SendPropertyChanging();
					this._udtrukket = value;
					this.SendPropertyChanged("udtrukket");
					this.OnudtrukketChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_leverancespecifikation", DbType="NVarChar(10)")]
		public string leverancespecifikation
		{
			get
			{
				return this._leverancespecifikation;
			}
			set
			{
				if ((this._leverancespecifikation != value))
				{
					this.OnleverancespecifikationChanging(value);
					this.SendPropertyChanging();
					this._leverancespecifikation = value;
					this.SendPropertyChanged("leverancespecifikation");
					this.OnleverancespecifikationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_leverancedannelsesdato", DbType="DateTime")]
		public System.Nullable<System.DateTime> leverancedannelsesdato
		{
			get
			{
				return this._leverancedannelsesdato;
			}
			set
			{
				if ((this._leverancedannelsesdato != value))
				{
					this.OnleverancedannelsesdatoChanging(value);
					this.SendPropertyChanging();
					this._leverancedannelsesdato = value;
					this.SendPropertyChanged("leverancedannelsesdato");
					this.OnleverancedannelsesdatoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblpbsforsendelse_tbltilpb", Storage="_tblpbsforsendelse", ThisKey="pbsforsendelseid", OtherKey="id", IsForeignKey=true, DeleteRule="CASCADE")]
		public tblpbsforsendelse tblpbsforsendelse
		{
			get
			{
				return this._tblpbsforsendelse.Entity;
			}
			set
			{
				tblpbsforsendelse previousValue = this._tblpbsforsendelse.Entity;
				if (((previousValue != value) 
							|| (this._tblpbsforsendelse.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblpbsforsendelse.Entity = null;
						previousValue.tbltilpbs.Remove(this);
					}
					this._tblpbsforsendelse.Entity = value;
					if ((value != null))
					{
						value.tbltilpbs.Add(this);
						this._pbsforsendelseid = value.id;
					}
					else
					{
						this._pbsforsendelseid = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblpbsforsendelse");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
