//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("dbTSModel", "FK_tblafstem_tblbankkonto", "tblafstem", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(nsPuls3060.tblafstem), "tblbankkonto", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(nsPuls3060.tblbankkonto), true)]
[assembly: EdmRelationshipAttribute("dbTSModel", "FK_tblafstem_tbltrans", "tblafstem", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(nsPuls3060.tblafstem), "tbltrans", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(nsPuls3060.tbltrans), true)]
[assembly: EdmRelationshipAttribute("dbTSModel", "FK_tblbilag_tblkaldder", "tblbilag", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(nsPuls3060.tblbilag), "tblkladder", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(nsPuls3060.tblkladder), true)]
[assembly: EdmRelationshipAttribute("dbTSModel", "FK_tblbilag_tbltrans", "tblbilag", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(nsPuls3060.tblbilag), "tbltrans", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(nsPuls3060.tbltrans), true)]
[assembly: EdmRelationshipAttribute("dbTSModel", "FK_tblwbilag_tblwkaldder", "tblwbilag", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(nsPuls3060.tblwbilag), "tblwkladder", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(nsPuls3060.tblwkladder), true)]

#endregion

namespace nsPuls3060
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class dbTSEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new dbTSEntities object using the connection string found in the 'dbTSEntities' section of the application configuration file.
        /// </summary>
        public dbTSEntities() : base("name=dbTSEntities", "dbTSEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new dbTSEntities object.
        /// </summary>
        public dbTSEntities(string connectionString) : base(connectionString, "dbTSEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new dbTSEntities object.
        /// </summary>
        public dbTSEntities(EntityConnection connection) : base(connection, "dbTSEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblafstem> tblafstem
        {
            get
            {
                if ((_tblafstem == null))
                {
                    _tblafstem = base.CreateObjectSet<tblafstem>("tblafstem");
                }
                return _tblafstem;
            }
        }
        private ObjectSet<tblafstem> _tblafstem;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblbankafsteminit> tblbankafsteminit
        {
            get
            {
                if ((_tblbankafsteminit == null))
                {
                    _tblbankafsteminit = base.CreateObjectSet<tblbankafsteminit>("tblbankafsteminit");
                }
                return _tblbankafsteminit;
            }
        }
        private ObjectSet<tblbankafsteminit> _tblbankafsteminit;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblbankkonto> tblbankkonto
        {
            get
            {
                if ((_tblbankkonto == null))
                {
                    _tblbankkonto = base.CreateObjectSet<tblbankkonto>("tblbankkonto");
                }
                return _tblbankkonto;
            }
        }
        private ObjectSet<tblbankkonto> _tblbankkonto;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblbilag> tblbilag
        {
            get
            {
                if ((_tblbilag == null))
                {
                    _tblbilag = base.CreateObjectSet<tblbilag>("tblbilag");
                }
                return _tblbilag;
            }
        }
        private ObjectSet<tblbilag> _tblbilag;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblkladder> tblkladder
        {
            get
            {
                if ((_tblkladder == null))
                {
                    _tblkladder = base.CreateObjectSet<tblkladder>("tblkladder");
                }
                return _tblkladder;
            }
        }
        private ObjectSet<tblkladder> _tblkladder;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblkonto> tblkonto
        {
            get
            {
                if ((_tblkonto == null))
                {
                    _tblkonto = base.CreateObjectSet<tblkonto>("tblkonto");
                }
                return _tblkonto;
            }
        }
        private ObjectSet<tblkonto> _tblkonto;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblnrserie> tblnrserie
        {
            get
            {
                if ((_tblnrserie == null))
                {
                    _tblnrserie = base.CreateObjectSet<tblnrserie>("tblnrserie");
                }
                return _tblnrserie;
            }
        }
        private ObjectSet<tblnrserie> _tblnrserie;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblregnskab> tblregnskab
        {
            get
            {
                if ((_tblregnskab == null))
                {
                    _tblregnskab = base.CreateObjectSet<tblregnskab>("tblregnskab");
                }
                return _tblregnskab;
            }
        }
        private ObjectSet<tblregnskab> _tblregnskab;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tbltrans> tbltrans
        {
            get
            {
                if ((_tbltrans == null))
                {
                    _tbltrans = base.CreateObjectSet<tbltrans>("tbltrans");
                }
                return _tbltrans;
            }
        }
        private ObjectSet<tbltrans> _tbltrans;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblwbilag> tblwbilag
        {
            get
            {
                if ((_tblwbilag == null))
                {
                    _tblwbilag = base.CreateObjectSet<tblwbilag>("tblwbilag");
                }
                return _tblwbilag;
            }
        }
        private ObjectSet<tblwbilag> _tblwbilag;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblwkladder> tblwkladder
        {
            get
            {
                if ((_tblwkladder == null))
                {
                    _tblwkladder = base.CreateObjectSet<tblwkladder>("tblwkladder");
                }
                return _tblwkladder;
            }
        }
        private ObjectSet<tblwkladder> _tblwkladder;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblafstem EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblafstem(tblafstem tblafstem)
        {
            base.AddObject("tblafstem", tblafstem);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblbankafsteminit EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblbankafsteminit(tblbankafsteminit tblbankafsteminit)
        {
            base.AddObject("tblbankafsteminit", tblbankafsteminit);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblbankkonto EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblbankkonto(tblbankkonto tblbankkonto)
        {
            base.AddObject("tblbankkonto", tblbankkonto);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblbilag EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblbilag(tblbilag tblbilag)
        {
            base.AddObject("tblbilag", tblbilag);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblkladder EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblkladder(tblkladder tblkladder)
        {
            base.AddObject("tblkladder", tblkladder);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblkonto EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblkonto(tblkonto tblkonto)
        {
            base.AddObject("tblkonto", tblkonto);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblnrserie EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblnrserie(tblnrserie tblnrserie)
        {
            base.AddObject("tblnrserie", tblnrserie);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblregnskab EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblregnskab(tblregnskab tblregnskab)
        {
            base.AddObject("tblregnskab", tblregnskab);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tbltrans EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotbltrans(tbltrans tbltrans)
        {
            base.AddObject("tbltrans", tbltrans);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblwbilag EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblwbilag(tblwbilag tblwbilag)
        {
            base.AddObject("tblwbilag", tblwbilag);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblwkladder EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblwkladder(tblwkladder tblwkladder)
        {
            base.AddObject("tblwkladder", tblwkladder);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbTSModel", Name="tblafstem")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblafstem : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblafstem object.
        /// </summary>
        /// <param name="pid">Initial value of the pid property.</param>
        public static tblafstem Createtblafstem(global::System.Int32 pid)
        {
            tblafstem tblafstem = new tblafstem();
            tblafstem.pid = pid;
            return tblafstem;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 pid
        {
            get
            {
                return _pid;
            }
            set
            {
                if (_pid != value)
                {
                    OnpidChanging(value);
                    ReportPropertyChanging("pid");
                    _pid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("pid");
                    OnpidChanged();
                }
            }
        }
        private global::System.Int32 _pid;
        partial void OnpidChanging(global::System.Int32 value);
        partial void OnpidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> udskriv
        {
            get
            {
                return _udskriv;
            }
            set
            {
                OnudskrivChanging(value);
                ReportPropertyChanging("udskriv");
                _udskriv = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("udskriv");
                OnudskrivChanged();
            }
        }
        private Nullable<global::System.Boolean> _udskriv;
        partial void OnudskrivChanging(Nullable<global::System.Boolean> value);
        partial void OnudskrivChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbTSModel", "FK_tblafstem_tblbankkonto", "tblbankkonto")]
        public EntityCollection<tblbankkonto> tblbankkonto
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tblbankkonto>("dbTSModel.FK_tblafstem_tblbankkonto", "tblbankkonto");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tblbankkonto>("dbTSModel.FK_tblafstem_tblbankkonto", "tblbankkonto", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbTSModel", "FK_tblafstem_tbltrans", "tbltrans")]
        public EntityCollection<tbltrans> tbltrans
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tbltrans>("dbTSModel.FK_tblafstem_tbltrans", "tbltrans");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tbltrans>("dbTSModel.FK_tblafstem_tbltrans", "tbltrans", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbTSModel", Name="tblbankafsteminit")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblbankafsteminit : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblbankafsteminit object.
        /// </summary>
        /// <param name="bid">Initial value of the bid property.</param>
        /// <param name="rid">Initial value of the rid property.</param>
        /// <param name="tid">Initial value of the tid property.</param>
        /// <param name="tnr">Initial value of the tnr property.</param>
        public static tblbankafsteminit Createtblbankafsteminit(global::System.Int32 bid, global::System.Int32 rid, global::System.Int32 tid, global::System.Int32 tnr)
        {
            tblbankafsteminit tblbankafsteminit = new tblbankafsteminit();
            tblbankafsteminit.bid = bid;
            tblbankafsteminit.rid = rid;
            tblbankafsteminit.tid = tid;
            tblbankafsteminit.tnr = tnr;
            return tblbankafsteminit;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 bid
        {
            get
            {
                return _bid;
            }
            set
            {
                if (_bid != value)
                {
                    OnbidChanging(value);
                    ReportPropertyChanging("bid");
                    _bid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("bid");
                    OnbidChanged();
                }
            }
        }
        private global::System.Int32 _bid;
        partial void OnbidChanging(global::System.Int32 value);
        partial void OnbidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 rid
        {
            get
            {
                return _rid;
            }
            set
            {
                if (_rid != value)
                {
                    OnridChanging(value);
                    ReportPropertyChanging("rid");
                    _rid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("rid");
                    OnridChanged();
                }
            }
        }
        private global::System.Int32 _rid;
        partial void OnridChanging(global::System.Int32 value);
        partial void OnridChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 tid
        {
            get
            {
                return _tid;
            }
            set
            {
                if (_tid != value)
                {
                    OntidChanging(value);
                    ReportPropertyChanging("tid");
                    _tid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("tid");
                    OntidChanged();
                }
            }
        }
        private global::System.Int32 _tid;
        partial void OntidChanging(global::System.Int32 value);
        partial void OntidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 tnr
        {
            get
            {
                return _tnr;
            }
            set
            {
                if (_tnr != value)
                {
                    OntnrChanging(value);
                    ReportPropertyChanging("tnr");
                    _tnr = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("tnr");
                    OntnrChanged();
                }
            }
        }
        private global::System.Int32 _tnr;
        partial void OntnrChanging(global::System.Int32 value);
        partial void OntnrChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbTSModel", Name="tblbankkonto")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblbankkonto : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblbankkonto object.
        /// </summary>
        /// <param name="pid">Initial value of the pid property.</param>
        public static tblbankkonto Createtblbankkonto(global::System.Int32 pid)
        {
            tblbankkonto tblbankkonto = new tblbankkonto();
            tblbankkonto.pid = pid;
            return tblbankkonto;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 pid
        {
            get
            {
                return _pid;
            }
            set
            {
                if (_pid != value)
                {
                    OnpidChanging(value);
                    ReportPropertyChanging("pid");
                    _pid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("pid");
                    OnpidChanged();
                }
            }
        }
        private global::System.Int32 _pid;
        partial void OnpidChanging(global::System.Int32 value);
        partial void OnpidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> saldo
        {
            get
            {
                return _saldo;
            }
            set
            {
                OnsaldoChanging(value);
                ReportPropertyChanging("saldo");
                _saldo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("saldo");
                OnsaldoChanged();
            }
        }
        private Nullable<global::System.Decimal> _saldo;
        partial void OnsaldoChanging(Nullable<global::System.Decimal> value);
        partial void OnsaldoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> skjul
        {
            get
            {
                return _skjul;
            }
            set
            {
                OnskjulChanging(value);
                ReportPropertyChanging("skjul");
                _skjul = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("skjul");
                OnskjulChanged();
            }
        }
        private Nullable<global::System.Boolean> _skjul;
        partial void OnskjulChanging(Nullable<global::System.Boolean> value);
        partial void OnskjulChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> dato
        {
            get
            {
                return _dato;
            }
            set
            {
                OndatoChanging(value);
                ReportPropertyChanging("dato");
                _dato = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dato");
                OndatoChanged();
            }
        }
        private Nullable<global::System.DateTime> _dato;
        partial void OndatoChanging(Nullable<global::System.DateTime> value);
        partial void OndatoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String tekst
        {
            get
            {
                return _tekst;
            }
            set
            {
                OntekstChanging(value);
                ReportPropertyChanging("tekst");
                _tekst = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("tekst");
                OntekstChanged();
            }
        }
        private global::System.String _tekst;
        partial void OntekstChanging(global::System.String value);
        partial void OntekstChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> belob
        {
            get
            {
                return _belob;
            }
            set
            {
                OnbelobChanging(value);
                ReportPropertyChanging("belob");
                _belob = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("belob");
                OnbelobChanged();
            }
        }
        private Nullable<global::System.Decimal> _belob;
        partial void OnbelobChanging(Nullable<global::System.Decimal> value);
        partial void OnbelobChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> afstem
        {
            get
            {
                return _afstem;
            }
            set
            {
                OnafstemChanging(value);
                ReportPropertyChanging("afstem");
                _afstem = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("afstem");
                OnafstemChanged();
            }
        }
        private Nullable<global::System.Int32> _afstem;
        partial void OnafstemChanging(Nullable<global::System.Int32> value);
        partial void OnafstemChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbTSModel", "FK_tblafstem_tblbankkonto", "tblafstem")]
        public tblafstem tblafstem
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblafstem>("dbTSModel.FK_tblafstem_tblbankkonto", "tblafstem").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblafstem>("dbTSModel.FK_tblafstem_tblbankkonto", "tblafstem").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblafstem> tblafstemReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblafstem>("dbTSModel.FK_tblafstem_tblbankkonto", "tblafstem");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblafstem>("dbTSModel.FK_tblafstem_tblbankkonto", "tblafstem", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbTSModel", Name="tblbilag")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblbilag : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblbilag object.
        /// </summary>
        /// <param name="pid">Initial value of the pid property.</param>
        public static tblbilag Createtblbilag(global::System.Int32 pid)
        {
            tblbilag tblbilag = new tblbilag();
            tblbilag.pid = pid;
            return tblbilag;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 pid
        {
            get
            {
                return _pid;
            }
            set
            {
                if (_pid != value)
                {
                    OnpidChanging(value);
                    ReportPropertyChanging("pid");
                    _pid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("pid");
                    OnpidChanged();
                }
            }
        }
        private global::System.Int32 _pid;
        partial void OnpidChanging(global::System.Int32 value);
        partial void OnpidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> regnskabid
        {
            get
            {
                return _regnskabid;
            }
            set
            {
                OnregnskabidChanging(value);
                ReportPropertyChanging("regnskabid");
                _regnskabid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("regnskabid");
                OnregnskabidChanged();
            }
        }
        private Nullable<global::System.Int32> _regnskabid;
        partial void OnregnskabidChanging(Nullable<global::System.Int32> value);
        partial void OnregnskabidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> bilag
        {
            get
            {
                return _bilag;
            }
            set
            {
                OnbilagChanging(value);
                ReportPropertyChanging("bilag");
                _bilag = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("bilag");
                OnbilagChanged();
            }
        }
        private Nullable<global::System.Int32> _bilag;
        partial void OnbilagChanging(Nullable<global::System.Int32> value);
        partial void OnbilagChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> dato
        {
            get
            {
                return _dato;
            }
            set
            {
                OndatoChanging(value);
                ReportPropertyChanging("dato");
                _dato = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dato");
                OndatoChanged();
            }
        }
        private Nullable<global::System.DateTime> _dato;
        partial void OndatoChanging(Nullable<global::System.DateTime> value);
        partial void OndatoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> udskriv
        {
            get
            {
                return _udskriv;
            }
            set
            {
                OnudskrivChanging(value);
                ReportPropertyChanging("udskriv");
                _udskriv = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("udskriv");
                OnudskrivChanged();
            }
        }
        private Nullable<global::System.Boolean> _udskriv;
        partial void OnudskrivChanging(Nullable<global::System.Boolean> value);
        partial void OnudskrivChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbTSModel", "FK_tblbilag_tblkaldder", "tblkladder")]
        public EntityCollection<tblkladder> tblkladder
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tblkladder>("dbTSModel.FK_tblbilag_tblkaldder", "tblkladder");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tblkladder>("dbTSModel.FK_tblbilag_tblkaldder", "tblkladder", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbTSModel", "FK_tblbilag_tbltrans", "tbltrans")]
        public EntityCollection<tbltrans> tbltrans
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tbltrans>("dbTSModel.FK_tblbilag_tbltrans", "tbltrans");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tbltrans>("dbTSModel.FK_tblbilag_tbltrans", "tbltrans", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbTSModel", Name="tblkladder")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblkladder : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblkladder object.
        /// </summary>
        /// <param name="pid">Initial value of the pid property.</param>
        public static tblkladder Createtblkladder(global::System.Int32 pid)
        {
            tblkladder tblkladder = new tblkladder();
            tblkladder.pid = pid;
            return tblkladder;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 pid
        {
            get
            {
                return _pid;
            }
            set
            {
                if (_pid != value)
                {
                    OnpidChanging(value);
                    ReportPropertyChanging("pid");
                    _pid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("pid");
                    OnpidChanged();
                }
            }
        }
        private global::System.Int32 _pid;
        partial void OnpidChanging(global::System.Int32 value);
        partial void OnpidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> regnskabid
        {
            get
            {
                return _regnskabid;
            }
            set
            {
                OnregnskabidChanging(value);
                ReportPropertyChanging("regnskabid");
                _regnskabid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("regnskabid");
                OnregnskabidChanged();
            }
        }
        private Nullable<global::System.Int32> _regnskabid;
        partial void OnregnskabidChanging(Nullable<global::System.Int32> value);
        partial void OnregnskabidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> bilagpid
        {
            get
            {
                return _bilagpid;
            }
            set
            {
                OnbilagpidChanging(value);
                ReportPropertyChanging("bilagpid");
                _bilagpid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("bilagpid");
                OnbilagpidChanged();
            }
        }
        private Nullable<global::System.Int32> _bilagpid;
        partial void OnbilagpidChanging(Nullable<global::System.Int32> value);
        partial void OnbilagpidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String tekst
        {
            get
            {
                return _tekst;
            }
            set
            {
                OntekstChanging(value);
                ReportPropertyChanging("tekst");
                _tekst = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("tekst");
                OntekstChanged();
            }
        }
        private global::System.String _tekst;
        partial void OntekstChanging(global::System.String value);
        partial void OntekstChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String afstemningskonto
        {
            get
            {
                return _afstemningskonto;
            }
            set
            {
                OnafstemningskontoChanging(value);
                ReportPropertyChanging("afstemningskonto");
                _afstemningskonto = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("afstemningskonto");
                OnafstemningskontoChanged();
            }
        }
        private global::System.String _afstemningskonto;
        partial void OnafstemningskontoChanging(global::System.String value);
        partial void OnafstemningskontoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> belob
        {
            get
            {
                return _belob;
            }
            set
            {
                OnbelobChanging(value);
                ReportPropertyChanging("belob");
                _belob = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("belob");
                OnbelobChanged();
            }
        }
        private Nullable<global::System.Decimal> _belob;
        partial void OnbelobChanging(Nullable<global::System.Decimal> value);
        partial void OnbelobChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> konto
        {
            get
            {
                return _konto;
            }
            set
            {
                OnkontoChanging(value);
                ReportPropertyChanging("konto");
                _konto = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("konto");
                OnkontoChanged();
            }
        }
        private Nullable<global::System.Int32> _konto;
        partial void OnkontoChanging(Nullable<global::System.Int32> value);
        partial void OnkontoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String momskode
        {
            get
            {
                return _momskode;
            }
            set
            {
                OnmomskodeChanging(value);
                ReportPropertyChanging("momskode");
                _momskode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("momskode");
                OnmomskodeChanged();
            }
        }
        private global::System.String _momskode;
        partial void OnmomskodeChanging(global::System.String value);
        partial void OnmomskodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> faktura
        {
            get
            {
                return _faktura;
            }
            set
            {
                OnfakturaChanging(value);
                ReportPropertyChanging("faktura");
                _faktura = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("faktura");
                OnfakturaChanged();
            }
        }
        private Nullable<global::System.Int32> _faktura;
        partial void OnfakturaChanging(Nullable<global::System.Int32> value);
        partial void OnfakturaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> id
        {
            get
            {
                return _id;
            }
            set
            {
                OnidChanging(value);
                ReportPropertyChanging("id");
                _id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id");
                OnidChanged();
            }
        }
        private Nullable<global::System.Int32> _id;
        partial void OnidChanging(Nullable<global::System.Int32> value);
        partial void OnidChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbTSModel", "FK_tblbilag_tblkaldder", "tblbilag")]
        public tblbilag tblbilag
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblbilag>("dbTSModel.FK_tblbilag_tblkaldder", "tblbilag").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblbilag>("dbTSModel.FK_tblbilag_tblkaldder", "tblbilag").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblbilag> tblbilagReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblbilag>("dbTSModel.FK_tblbilag_tblkaldder", "tblbilag");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblbilag>("dbTSModel.FK_tblbilag_tblkaldder", "tblbilag", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbTSModel", Name="tblkonto")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblkonto : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblkonto object.
        /// </summary>
        /// <param name="kontonr">Initial value of the kontonr property.</param>
        public static tblkonto Createtblkonto(global::System.Int32 kontonr)
        {
            tblkonto tblkonto = new tblkonto();
            tblkonto.kontonr = kontonr;
            return tblkonto;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 kontonr
        {
            get
            {
                return _kontonr;
            }
            set
            {
                if (_kontonr != value)
                {
                    OnkontonrChanging(value);
                    ReportPropertyChanging("kontonr");
                    _kontonr = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("kontonr");
                    OnkontonrChanged();
                }
            }
        }
        private global::System.Int32 _kontonr;
        partial void OnkontonrChanging(global::System.Int32 value);
        partial void OnkontonrChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String kontonavn
        {
            get
            {
                return _kontonavn;
            }
            set
            {
                OnkontonavnChanging(value);
                ReportPropertyChanging("kontonavn");
                _kontonavn = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("kontonavn");
                OnkontonavnChanged();
            }
        }
        private global::System.String _kontonavn;
        partial void OnkontonavnChanging(global::System.String value);
        partial void OnkontonavnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String type
        {
            get
            {
                return _type;
            }
            set
            {
                OntypeChanging(value);
                ReportPropertyChanging("type");
                _type = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("type");
                OntypeChanged();
            }
        }
        private global::System.String _type;
        partial void OntypeChanging(global::System.String value);
        partial void OntypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String momskode
        {
            get
            {
                return _momskode;
            }
            set
            {
                OnmomskodeChanging(value);
                ReportPropertyChanging("momskode");
                _momskode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("momskode");
                OnmomskodeChanged();
            }
        }
        private global::System.String _momskode;
        partial void OnmomskodeChanging(global::System.String value);
        partial void OnmomskodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> saldo
        {
            get
            {
                return _saldo;
            }
            set
            {
                OnsaldoChanging(value);
                ReportPropertyChanging("saldo");
                _saldo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("saldo");
                OnsaldoChanged();
            }
        }
        private Nullable<global::System.Decimal> _saldo;
        partial void OnsaldoChanging(Nullable<global::System.Decimal> value);
        partial void OnsaldoChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbTSModel", Name="tblnrserie")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblnrserie : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblnrserie object.
        /// </summary>
        /// <param name="nrserienavn">Initial value of the nrserienavn property.</param>
        public static tblnrserie Createtblnrserie(global::System.String nrserienavn)
        {
            tblnrserie tblnrserie = new tblnrserie();
            tblnrserie.nrserienavn = nrserienavn;
            return tblnrserie;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nrserienavn
        {
            get
            {
                return _nrserienavn;
            }
            set
            {
                if (_nrserienavn != value)
                {
                    OnnrserienavnChanging(value);
                    ReportPropertyChanging("nrserienavn");
                    _nrserienavn = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("nrserienavn");
                    OnnrserienavnChanged();
                }
            }
        }
        private global::System.String _nrserienavn;
        partial void OnnrserienavnChanging(global::System.String value);
        partial void OnnrserienavnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> sidstbrugtenr
        {
            get
            {
                return _sidstbrugtenr;
            }
            set
            {
                OnsidstbrugtenrChanging(value);
                ReportPropertyChanging("sidstbrugtenr");
                _sidstbrugtenr = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("sidstbrugtenr");
                OnsidstbrugtenrChanged();
            }
        }
        private Nullable<global::System.Int32> _sidstbrugtenr;
        partial void OnsidstbrugtenrChanging(Nullable<global::System.Int32> value);
        partial void OnsidstbrugtenrChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbTSModel", Name="tblregnskab")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblregnskab : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblregnskab object.
        /// </summary>
        /// <param name="rid">Initial value of the rid property.</param>
        public static tblregnskab Createtblregnskab(global::System.Int32 rid)
        {
            tblregnskab tblregnskab = new tblregnskab();
            tblregnskab.rid = rid;
            return tblregnskab;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 rid
        {
            get
            {
                return _rid;
            }
            set
            {
                if (_rid != value)
                {
                    OnridChanging(value);
                    ReportPropertyChanging("rid");
                    _rid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("rid");
                    OnridChanged();
                }
            }
        }
        private global::System.Int32 _rid;
        partial void OnridChanging(global::System.Int32 value);
        partial void OnridChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String navn
        {
            get
            {
                return _navn;
            }
            set
            {
                OnnavnChanging(value);
                ReportPropertyChanging("navn");
                _navn = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("navn");
                OnnavnChanged();
            }
        }
        private global::System.String _navn;
        partial void OnnavnChanging(global::System.String value);
        partial void OnnavnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> oprettet
        {
            get
            {
                return _oprettet;
            }
            set
            {
                OnoprettetChanging(value);
                ReportPropertyChanging("oprettet");
                _oprettet = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("oprettet");
                OnoprettetChanged();
            }
        }
        private Nullable<global::System.DateTime> _oprettet;
        partial void OnoprettetChanging(Nullable<global::System.DateTime> value);
        partial void OnoprettetChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> start
        {
            get
            {
                return _start;
            }
            set
            {
                OnstartChanging(value);
                ReportPropertyChanging("start");
                _start = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("start");
                OnstartChanged();
            }
        }
        private Nullable<global::System.DateTime> _start;
        partial void OnstartChanging(Nullable<global::System.DateTime> value);
        partial void OnstartChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> slut
        {
            get
            {
                return _slut;
            }
            set
            {
                OnslutChanging(value);
                ReportPropertyChanging("slut");
                _slut = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("slut");
                OnslutChanged();
            }
        }
        private Nullable<global::System.DateTime> _slut;
        partial void OnslutChanging(Nullable<global::System.DateTime> value);
        partial void OnslutChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> datoLaas
        {
            get
            {
                return _datoLaas;
            }
            set
            {
                OndatoLaasChanging(value);
                ReportPropertyChanging("datoLaas");
                _datoLaas = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("datoLaas");
                OndatoLaasChanged();
            }
        }
        private Nullable<global::System.DateTime> _datoLaas;
        partial void OndatoLaasChanging(Nullable<global::System.DateTime> value);
        partial void OndatoLaasChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String firmanavn
        {
            get
            {
                return _firmanavn;
            }
            set
            {
                OnfirmanavnChanging(value);
                ReportPropertyChanging("firmanavn");
                _firmanavn = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("firmanavn");
                OnfirmanavnChanged();
            }
        }
        private global::System.String _firmanavn;
        partial void OnfirmanavnChanging(global::System.String value);
        partial void OnfirmanavnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String placering
        {
            get
            {
                return _placering;
            }
            set
            {
                OnplaceringChanging(value);
                ReportPropertyChanging("placering");
                _placering = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("placering");
                OnplaceringChanged();
            }
        }
        private global::System.String _placering;
        partial void OnplaceringChanging(global::System.String value);
        partial void OnplaceringChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String eksportmappe
        {
            get
            {
                return _eksportmappe;
            }
            set
            {
                OneksportmappeChanging(value);
                ReportPropertyChanging("eksportmappe");
                _eksportmappe = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("eksportmappe");
                OneksportmappeChanged();
            }
        }
        private global::System.String _eksportmappe;
        partial void OneksportmappeChanging(global::System.String value);
        partial void OneksportmappeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> afsluttet
        {
            get
            {
                return _afsluttet;
            }
            set
            {
                OnafsluttetChanging(value);
                ReportPropertyChanging("afsluttet");
                _afsluttet = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("afsluttet");
                OnafsluttetChanged();
            }
        }
        private Nullable<global::System.Boolean> _afsluttet;
        partial void OnafsluttetChanging(Nullable<global::System.Boolean> value);
        partial void OnafsluttetChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbTSModel", Name="tbltrans")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbltrans : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tbltrans object.
        /// </summary>
        /// <param name="pid">Initial value of the pid property.</param>
        public static tbltrans Createtbltrans(global::System.Int32 pid)
        {
            tbltrans tbltrans = new tbltrans();
            tbltrans.pid = pid;
            return tbltrans;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 pid
        {
            get
            {
                return _pid;
            }
            set
            {
                if (_pid != value)
                {
                    OnpidChanging(value);
                    ReportPropertyChanging("pid");
                    _pid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("pid");
                    OnpidChanged();
                }
            }
        }
        private global::System.Int32 _pid;
        partial void OnpidChanging(global::System.Int32 value);
        partial void OnpidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> regnskabid
        {
            get
            {
                return _regnskabid;
            }
            set
            {
                OnregnskabidChanging(value);
                ReportPropertyChanging("regnskabid");
                _regnskabid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("regnskabid");
                OnregnskabidChanged();
            }
        }
        private Nullable<global::System.Int32> _regnskabid;
        partial void OnregnskabidChanging(Nullable<global::System.Int32> value);
        partial void OnregnskabidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> skjul
        {
            get
            {
                return _skjul;
            }
            set
            {
                OnskjulChanging(value);
                ReportPropertyChanging("skjul");
                _skjul = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("skjul");
                OnskjulChanged();
            }
        }
        private Nullable<global::System.Boolean> _skjul;
        partial void OnskjulChanging(Nullable<global::System.Boolean> value);
        partial void OnskjulChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> bilagpid
        {
            get
            {
                return _bilagpid;
            }
            set
            {
                OnbilagpidChanging(value);
                ReportPropertyChanging("bilagpid");
                _bilagpid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("bilagpid");
                OnbilagpidChanged();
            }
        }
        private Nullable<global::System.Int32> _bilagpid;
        partial void OnbilagpidChanging(Nullable<global::System.Int32> value);
        partial void OnbilagpidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String tekst
        {
            get
            {
                return _tekst;
            }
            set
            {
                OntekstChanging(value);
                ReportPropertyChanging("tekst");
                _tekst = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("tekst");
                OntekstChanged();
            }
        }
        private global::System.String _tekst;
        partial void OntekstChanging(global::System.String value);
        partial void OntekstChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> kontonr
        {
            get
            {
                return _kontonr;
            }
            set
            {
                OnkontonrChanging(value);
                ReportPropertyChanging("kontonr");
                _kontonr = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("kontonr");
                OnkontonrChanged();
            }
        }
        private Nullable<global::System.Int32> _kontonr;
        partial void OnkontonrChanging(Nullable<global::System.Int32> value);
        partial void OnkontonrChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String kontonavn
        {
            get
            {
                return _kontonavn;
            }
            set
            {
                OnkontonavnChanging(value);
                ReportPropertyChanging("kontonavn");
                _kontonavn = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("kontonavn");
                OnkontonavnChanged();
            }
        }
        private global::System.String _kontonavn;
        partial void OnkontonavnChanging(global::System.String value);
        partial void OnkontonavnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> moms
        {
            get
            {
                return _moms;
            }
            set
            {
                OnmomsChanging(value);
                ReportPropertyChanging("moms");
                _moms = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("moms");
                OnmomsChanged();
            }
        }
        private Nullable<global::System.Decimal> _moms;
        partial void OnmomsChanging(Nullable<global::System.Decimal> value);
        partial void OnmomsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> debet
        {
            get
            {
                return _debet;
            }
            set
            {
                OndebetChanging(value);
                ReportPropertyChanging("debet");
                _debet = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("debet");
                OndebetChanged();
            }
        }
        private Nullable<global::System.Decimal> _debet;
        partial void OndebetChanging(Nullable<global::System.Decimal> value);
        partial void OndebetChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> kredit
        {
            get
            {
                return _kredit;
            }
            set
            {
                OnkreditChanging(value);
                ReportPropertyChanging("kredit");
                _kredit = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("kredit");
                OnkreditChanged();
            }
        }
        private Nullable<global::System.Decimal> _kredit;
        partial void OnkreditChanging(Nullable<global::System.Decimal> value);
        partial void OnkreditChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> id
        {
            get
            {
                return _id;
            }
            set
            {
                OnidChanging(value);
                ReportPropertyChanging("id");
                _id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id");
                OnidChanged();
            }
        }
        private Nullable<global::System.Int32> _id;
        partial void OnidChanging(Nullable<global::System.Int32> value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> nr
        {
            get
            {
                return _nr;
            }
            set
            {
                OnnrChanging(value);
                ReportPropertyChanging("nr");
                _nr = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("nr");
                OnnrChanged();
            }
        }
        private Nullable<global::System.Int32> _nr;
        partial void OnnrChanging(Nullable<global::System.Int32> value);
        partial void OnnrChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> belob
        {
            get
            {
                return _belob;
            }
            set
            {
                OnbelobChanging(value);
                ReportPropertyChanging("belob");
                _belob = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("belob");
                OnbelobChanged();
            }
        }
        private Nullable<global::System.Decimal> _belob;
        partial void OnbelobChanging(Nullable<global::System.Decimal> value);
        partial void OnbelobChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> afstem
        {
            get
            {
                return _afstem;
            }
            set
            {
                OnafstemChanging(value);
                ReportPropertyChanging("afstem");
                _afstem = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("afstem");
                OnafstemChanged();
            }
        }
        private Nullable<global::System.Int32> _afstem;
        partial void OnafstemChanging(Nullable<global::System.Int32> value);
        partial void OnafstemChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbTSModel", "FK_tblafstem_tbltrans", "tblafstem")]
        public tblafstem tblafstem
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblafstem>("dbTSModel.FK_tblafstem_tbltrans", "tblafstem").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblafstem>("dbTSModel.FK_tblafstem_tbltrans", "tblafstem").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblafstem> tblafstemReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblafstem>("dbTSModel.FK_tblafstem_tbltrans", "tblafstem");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblafstem>("dbTSModel.FK_tblafstem_tbltrans", "tblafstem", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbTSModel", "FK_tblbilag_tbltrans", "tblbilag")]
        public tblbilag tblbilag
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblbilag>("dbTSModel.FK_tblbilag_tbltrans", "tblbilag").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblbilag>("dbTSModel.FK_tblbilag_tbltrans", "tblbilag").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblbilag> tblbilagReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblbilag>("dbTSModel.FK_tblbilag_tbltrans", "tblbilag");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblbilag>("dbTSModel.FK_tblbilag_tbltrans", "tblbilag", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbTSModel", Name="tblwbilag")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblwbilag : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblwbilag object.
        /// </summary>
        /// <param name="pid">Initial value of the pid property.</param>
        /// <param name="bilag">Initial value of the bilag property.</param>
        /// <param name="dato">Initial value of the dato property.</param>
        public static tblwbilag Createtblwbilag(global::System.Int32 pid, global::System.Int32 bilag, global::System.DateTime dato)
        {
            tblwbilag tblwbilag = new tblwbilag();
            tblwbilag.pid = pid;
            tblwbilag.bilag = bilag;
            tblwbilag.dato = dato;
            return tblwbilag;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 pid
        {
            get
            {
                return _pid;
            }
            set
            {
                if (_pid != value)
                {
                    OnpidChanging(value);
                    ReportPropertyChanging("pid");
                    _pid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("pid");
                    OnpidChanged();
                }
            }
        }
        private global::System.Int32 _pid;
        partial void OnpidChanging(global::System.Int32 value);
        partial void OnpidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 bilag
        {
            get
            {
                return _bilag;
            }
            set
            {
                OnbilagChanging(value);
                ReportPropertyChanging("bilag");
                _bilag = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("bilag");
                OnbilagChanged();
            }
        }
        private global::System.Int32 _bilag;
        partial void OnbilagChanging(global::System.Int32 value);
        partial void OnbilagChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime dato
        {
            get
            {
                return _dato;
            }
            set
            {
                OndatoChanging(value);
                ReportPropertyChanging("dato");
                _dato = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dato");
                OndatoChanged();
            }
        }
        private global::System.DateTime _dato;
        partial void OndatoChanging(global::System.DateTime value);
        partial void OndatoChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbTSModel", "FK_tblwbilag_tblwkaldder", "tblwkladder")]
        public EntityCollection<tblwkladder> tblwkladder
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tblwkladder>("dbTSModel.FK_tblwbilag_tblwkaldder", "tblwkladder");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tblwkladder>("dbTSModel.FK_tblwbilag_tblwkaldder", "tblwkladder", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbTSModel", Name="tblwkladder")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblwkladder : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblwkladder object.
        /// </summary>
        /// <param name="pid">Initial value of the pid property.</param>
        /// <param name="bilagpid">Initial value of the bilagpid property.</param>
        public static tblwkladder Createtblwkladder(global::System.Int32 pid, global::System.Int32 bilagpid)
        {
            tblwkladder tblwkladder = new tblwkladder();
            tblwkladder.pid = pid;
            tblwkladder.bilagpid = bilagpid;
            return tblwkladder;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 pid
        {
            get
            {
                return _pid;
            }
            set
            {
                if (_pid != value)
                {
                    OnpidChanging(value);
                    ReportPropertyChanging("pid");
                    _pid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("pid");
                    OnpidChanged();
                }
            }
        }
        private global::System.Int32 _pid;
        partial void OnpidChanging(global::System.Int32 value);
        partial void OnpidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 bilagpid
        {
            get
            {
                return _bilagpid;
            }
            set
            {
                OnbilagpidChanging(value);
                ReportPropertyChanging("bilagpid");
                _bilagpid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("bilagpid");
                OnbilagpidChanged();
            }
        }
        private global::System.Int32 _bilagpid;
        partial void OnbilagpidChanging(global::System.Int32 value);
        partial void OnbilagpidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String tekst
        {
            get
            {
                return _tekst;
            }
            set
            {
                OntekstChanging(value);
                ReportPropertyChanging("tekst");
                _tekst = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("tekst");
                OntekstChanged();
            }
        }
        private global::System.String _tekst;
        partial void OntekstChanging(global::System.String value);
        partial void OntekstChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String afstemningskonto
        {
            get
            {
                return _afstemningskonto;
            }
            set
            {
                OnafstemningskontoChanging(value);
                ReportPropertyChanging("afstemningskonto");
                _afstemningskonto = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("afstemningskonto");
                OnafstemningskontoChanged();
            }
        }
        private global::System.String _afstemningskonto;
        partial void OnafstemningskontoChanging(global::System.String value);
        partial void OnafstemningskontoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> belob
        {
            get
            {
                return _belob;
            }
            set
            {
                OnbelobChanging(value);
                ReportPropertyChanging("belob");
                _belob = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("belob");
                OnbelobChanged();
            }
        }
        private Nullable<global::System.Decimal> _belob;
        partial void OnbelobChanging(Nullable<global::System.Decimal> value);
        partial void OnbelobChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> konto
        {
            get
            {
                return _konto;
            }
            set
            {
                OnkontoChanging(value);
                ReportPropertyChanging("konto");
                _konto = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("konto");
                OnkontoChanged();
            }
        }
        private Nullable<global::System.Int32> _konto;
        partial void OnkontoChanging(Nullable<global::System.Int32> value);
        partial void OnkontoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String momskode
        {
            get
            {
                return _momskode;
            }
            set
            {
                OnmomskodeChanging(value);
                ReportPropertyChanging("momskode");
                _momskode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("momskode");
                OnmomskodeChanged();
            }
        }
        private global::System.String _momskode;
        partial void OnmomskodeChanging(global::System.String value);
        partial void OnmomskodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> faktura
        {
            get
            {
                return _faktura;
            }
            set
            {
                OnfakturaChanging(value);
                ReportPropertyChanging("faktura");
                _faktura = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("faktura");
                OnfakturaChanged();
            }
        }
        private Nullable<global::System.Int32> _faktura;
        partial void OnfakturaChanging(Nullable<global::System.Int32> value);
        partial void OnfakturaChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbTSModel", "FK_tblwbilag_tblwkaldder", "tblwbilag")]
        public tblwbilag tblwbilag
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblwbilag>("dbTSModel.FK_tblwbilag_tblwkaldder", "tblwbilag").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblwbilag>("dbTSModel.FK_tblwbilag_tblwkaldder", "tblwbilag").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblwbilag> tblwbilagReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblwbilag>("dbTSModel.FK_tblwbilag_tblwkaldder", "tblwbilag");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblwbilag>("dbTSModel.FK_tblwbilag_tblwkaldder", "tblwbilag", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
