

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    public sealed partial class tblFeatureRelation : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.tblFeatureRelation, global::LightSwitchApplication.tblFeatureRelation.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the tblFeatureRelation entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public tblFeatureRelation()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public tblFeatureRelation(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.tblFeatureRelation> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.tblFeatureRelation.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void tblFeatureRelation_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void tblFeatureRelation_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.tblFeatureRelation.DetailsClass.GetValue(this, global::LightSwitchApplication.tblFeatureRelation.DetailsClass.PropertySetProperties.Id);
            }
            set
            {
                global::LightSwitchApplication.tblFeatureRelation.DetailsClass.SetValue(this, global::LightSwitchApplication.tblFeatureRelation.DetailsClass.PropertySetProperties.Id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string CreatedBy
        {
            get
            {
                return global::LightSwitchApplication.tblFeatureRelation.DetailsClass.GetValue(this, global::LightSwitchApplication.tblFeatureRelation.DetailsClass.PropertySetProperties.CreatedBy);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTimeOffset> Created
        {
            get
            {
                return global::LightSwitchApplication.tblFeatureRelation.DetailsClass.GetValue(this, global::LightSwitchApplication.tblFeatureRelation.DetailsClass.PropertySetProperties.Created);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string ModifiedBy
        {
            get
            {
                return global::LightSwitchApplication.tblFeatureRelation.DetailsClass.GetValue(this, global::LightSwitchApplication.tblFeatureRelation.DetailsClass.PropertySetProperties.ModifiedBy);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTimeOffset> Modified
        {
            get
            {
                return global::LightSwitchApplication.tblFeatureRelation.DetailsClass.GetValue(this, global::LightSwitchApplication.tblFeatureRelation.DetailsClass.PropertySetProperties.Modified);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public byte[] RowVersion
        {
            get
            {
                return global::LightSwitchApplication.tblFeatureRelation.DetailsClass.GetValue(this, global::LightSwitchApplication.tblFeatureRelation.DetailsClass.PropertySetProperties.RowVersion);
            }
            set
            {
                global::LightSwitchApplication.tblFeatureRelation.DetailsClass.SetValue(this, global::LightSwitchApplication.tblFeatureRelation.DetailsClass.PropertySetProperties.RowVersion, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.tblFeature tblFeature
        {
            get
            {
                return global::LightSwitchApplication.tblFeatureRelation.DetailsClass.GetValue(this, global::LightSwitchApplication.tblFeatureRelation.DetailsClass.PropertySetProperties.tblFeature);
            }
            set
            {
                global::LightSwitchApplication.tblFeatureRelation.DetailsClass.SetValue(this, global::LightSwitchApplication.tblFeatureRelation.DetailsClass.PropertySetProperties.tblFeature, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void tblFeature_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void tblFeature_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void tblFeature_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.tblComputer tblComputer
        {
            get
            {
                return global::LightSwitchApplication.tblFeatureRelation.DetailsClass.GetValue(this, global::LightSwitchApplication.tblFeatureRelation.DetailsClass.PropertySetProperties.tblComputer);
            }
            set
            {
                global::LightSwitchApplication.tblFeatureRelation.DetailsClass.SetValue(this, global::LightSwitchApplication.tblFeatureRelation.DetailsClass.PropertySetProperties.tblComputer, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void tblComputer_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void tblComputer_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void tblComputer_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.tblFeatureRelation,
                global::LightSwitchApplication.tblFeatureRelation.DetailsClass,
                global::LightSwitchApplication.tblFeatureRelation.DetailsClass.IImplementation,
                global::LightSwitchApplication.tblFeatureRelation.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.tblFeatureRelation, global::LightSwitchApplication.tblFeatureRelation.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.tblFeatureRelation, global::LightSwitchApplication.tblFeatureRelation.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.tblFeatureRelation.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.tblFeatureRelation, global::LightSwitchApplication.tblFeatureRelation.DetailsClass>.Entry
                __tblFeatureRelationEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.tblFeatureRelation, global::LightSwitchApplication.tblFeatureRelation.DetailsClass>.Entry(
                    global::LightSwitchApplication.tblFeatureRelation.DetailsClass.__tblFeatureRelation_CreateNew,
                    global::LightSwitchApplication.tblFeatureRelation.DetailsClass.__tblFeatureRelation_Created,
                    global::LightSwitchApplication.tblFeatureRelation.DetailsClass.__tblFeatureRelation_AllowSaveWithErrors);
            private static global::LightSwitchApplication.tblFeatureRelation __tblFeatureRelation_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.tblFeatureRelation> es)
            {
                return new global::LightSwitchApplication.tblFeatureRelation(es);
            }
            private static void __tblFeatureRelation_Created(global::LightSwitchApplication.tblFeatureRelation e)
            {
                e.tblFeatureRelation_Created();
            }
            private static bool __tblFeatureRelation_AllowSaveWithErrors(global::LightSwitchApplication.tblFeatureRelation e)
            {
                bool result = false;
                e.tblFeatureRelation_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.tblFeatureRelation, global::LightSwitchApplication.tblFeatureRelation.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.tblFeatureRelation, global::LightSwitchApplication.tblFeatureRelation.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.tblFeatureRelation.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.tblFeatureRelation, global::LightSwitchApplication.tblFeatureRelation.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblFeatureRelation, global::LightSwitchApplication.tblFeatureRelation.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.tblFeatureRelation.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblFeatureRelation, global::LightSwitchApplication.tblFeatureRelation.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblFeatureRelation, global::LightSwitchApplication.tblFeatureRelation.DetailsClass, string> CreatedBy
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.tblFeatureRelation.DetailsClass.PropertySetProperties.CreatedBy) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblFeatureRelation, global::LightSwitchApplication.tblFeatureRelation.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblFeatureRelation, global::LightSwitchApplication.tblFeatureRelation.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>> Created
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.tblFeatureRelation.DetailsClass.PropertySetProperties.Created) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblFeatureRelation, global::LightSwitchApplication.tblFeatureRelation.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblFeatureRelation, global::LightSwitchApplication.tblFeatureRelation.DetailsClass, string> ModifiedBy
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.tblFeatureRelation.DetailsClass.PropertySetProperties.ModifiedBy) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblFeatureRelation, global::LightSwitchApplication.tblFeatureRelation.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblFeatureRelation, global::LightSwitchApplication.tblFeatureRelation.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>> Modified
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.tblFeatureRelation.DetailsClass.PropertySetProperties.Modified) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblFeatureRelation, global::LightSwitchApplication.tblFeatureRelation.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblFeatureRelation, global::LightSwitchApplication.tblFeatureRelation.DetailsClass, byte[]> RowVersion
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.tblFeatureRelation.DetailsClass.PropertySetProperties.RowVersion) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblFeatureRelation, global::LightSwitchApplication.tblFeatureRelation.DetailsClass, byte[]>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.tblFeatureRelation, global::LightSwitchApplication.tblFeatureRelation.DetailsClass, global::LightSwitchApplication.tblFeature> tblFeature
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.tblFeatureRelation.DetailsClass.PropertySetProperties.tblFeature) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.tblFeatureRelation, global::LightSwitchApplication.tblFeatureRelation.DetailsClass, global::LightSwitchApplication.tblFeature>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.tblFeatureRelation, global::LightSwitchApplication.tblFeatureRelation.DetailsClass, global::LightSwitchApplication.tblComputer> tblComputer
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.tblFeatureRelation.DetailsClass.PropertySetProperties.tblComputer) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.tblFeatureRelation, global::LightSwitchApplication.tblFeatureRelation.DetailsClass, global::LightSwitchApplication.tblComputer>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; set; }
                new string CreatedBy { get; }
                new global::System.Nullable<global::System.DateTimeOffset> Created { get; }
                new string ModifiedBy { get; }
                new global::System.Nullable<global::System.DateTimeOffset> Modified { get; }
                new byte[] RowVersion { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation tblFeature { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation tblComputer { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblFeatureRelation, global::LightSwitchApplication.tblFeatureRelation.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblFeatureRelation, global::LightSwitchApplication.tblFeatureRelation.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.tblFeatureRelation.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.tblFeatureRelation.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.tblFeatureRelation.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.tblFeatureRelation.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        global::LightSwitchApplication.tblFeatureRelation.DetailsClass.PropertySetProperties._Id_SetImplementationValue,
                        global::LightSwitchApplication.tblFeatureRelation.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.tblFeatureRelation.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblFeatureRelation, global::LightSwitchApplication.tblFeatureRelation.DetailsClass, int>.Data> c, global::LightSwitchApplication.tblFeatureRelation.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.tblFeatureRelation e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.tblFeatureRelation e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.tblFeatureRelation.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_SetImplementationValue(global::LightSwitchApplication.tblFeatureRelation.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Id = v;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.tblFeatureRelation e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblFeatureRelation, global::LightSwitchApplication.tblFeatureRelation.DetailsClass, string>.Entry
                    CreatedBy = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblFeatureRelation, global::LightSwitchApplication.tblFeatureRelation.DetailsClass, string>.Entry(
                        "CreatedBy",
                        global::LightSwitchApplication.tblFeatureRelation.DetailsClass.PropertySetProperties._CreatedBy_Stub,
                        global::LightSwitchApplication.tblFeatureRelation.DetailsClass.PropertySetProperties._CreatedBy_ComputeIsReadOnly,
                        global::LightSwitchApplication.tblFeatureRelation.DetailsClass.PropertySetProperties._CreatedBy_Validate,
                        global::LightSwitchApplication.tblFeatureRelation.DetailsClass.PropertySetProperties._CreatedBy_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.tblFeatureRelation.DetailsClass.PropertySetProperties._CreatedBy_OnValueChanged);
                private static void _CreatedBy_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.tblFeatureRelation.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblFeatureRelation, global::LightSwitchApplication.tblFeatureRelation.DetailsClass, string>.Data> c, global::LightSwitchApplication.tblFeatureRelation.DetailsClass d, object sf)
                {
                    c(d, ref d._CreatedBy, sf);
                }
                private static bool _CreatedBy_ComputeIsReadOnly(global::LightSwitchApplication.tblFeatureRelation e)
                {
                    bool result = false;
                    e.CreatedBy_IsReadOnly(ref result);
                    return result;
                }
                private static void _CreatedBy_Validate(global::LightSwitchApplication.tblFeatureRelation e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.CreatedBy_Validate(r);
                }
                private static string _CreatedBy_GetImplementationValue(global::LightSwitchApplication.tblFeatureRelation.DetailsClass d)
                {
                    return d.ImplementationEntity.CreatedBy;
                }
                private static void _CreatedBy_OnValueChanged(global::LightSwitchApplication.tblFeatureRelation e)
                {
                    e.CreatedBy_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblFeatureRelation, global::LightSwitchApplication.tblFeatureRelation.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry
                    Created = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblFeatureRelation, global::LightSwitchApplication.tblFeatureRelation.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry(
                        "Created",
                        global::LightSwitchApplication.tblFeatureRelation.DetailsClass.PropertySetProperties._Created_Stub,
                        global::LightSwitchApplication.tblFeatureRelation.DetailsClass.PropertySetProperties._Created_ComputeIsReadOnly,
                        global::LightSwitchApplication.tblFeatureRelation.DetailsClass.PropertySetProperties._Created_Validate,
                        global::LightSwitchApplication.tblFeatureRelation.DetailsClass.PropertySetProperties._Created_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.tblFeatureRelation.DetailsClass.PropertySetProperties._Created_OnValueChanged);
                private static void _Created_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.tblFeatureRelation.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblFeatureRelation, global::LightSwitchApplication.tblFeatureRelation.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data> c, global::LightSwitchApplication.tblFeatureRelation.DetailsClass d, object sf)
                {
                    c(d, ref d._Created, sf);
                }
                private static bool _Created_ComputeIsReadOnly(global::LightSwitchApplication.tblFeatureRelation e)
                {
                    bool result = false;
                    e.Created_IsReadOnly(ref result);
                    return result;
                }
                private static void _Created_Validate(global::LightSwitchApplication.tblFeatureRelation e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Created_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTimeOffset> _Created_GetImplementationValue(global::LightSwitchApplication.tblFeatureRelation.DetailsClass d)
                {
                    return d.ImplementationEntity.Created;
                }
                private static void _Created_OnValueChanged(global::LightSwitchApplication.tblFeatureRelation e)
                {
                    e.Created_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblFeatureRelation, global::LightSwitchApplication.tblFeatureRelation.DetailsClass, string>.Entry
                    ModifiedBy = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblFeatureRelation, global::LightSwitchApplication.tblFeatureRelation.DetailsClass, string>.Entry(
                        "ModifiedBy",
                        global::LightSwitchApplication.tblFeatureRelation.DetailsClass.PropertySetProperties._ModifiedBy_Stub,
                        global::LightSwitchApplication.tblFeatureRelation.DetailsClass.PropertySetProperties._ModifiedBy_ComputeIsReadOnly,
                        global::LightSwitchApplication.tblFeatureRelation.DetailsClass.PropertySetProperties._ModifiedBy_Validate,
                        global::LightSwitchApplication.tblFeatureRelation.DetailsClass.PropertySetProperties._ModifiedBy_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.tblFeatureRelation.DetailsClass.PropertySetProperties._ModifiedBy_OnValueChanged);
                private static void _ModifiedBy_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.tblFeatureRelation.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblFeatureRelation, global::LightSwitchApplication.tblFeatureRelation.DetailsClass, string>.Data> c, global::LightSwitchApplication.tblFeatureRelation.DetailsClass d, object sf)
                {
                    c(d, ref d._ModifiedBy, sf);
                }
                private static bool _ModifiedBy_ComputeIsReadOnly(global::LightSwitchApplication.tblFeatureRelation e)
                {
                    bool result = false;
                    e.ModifiedBy_IsReadOnly(ref result);
                    return result;
                }
                private static void _ModifiedBy_Validate(global::LightSwitchApplication.tblFeatureRelation e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ModifiedBy_Validate(r);
                }
                private static string _ModifiedBy_GetImplementationValue(global::LightSwitchApplication.tblFeatureRelation.DetailsClass d)
                {
                    return d.ImplementationEntity.ModifiedBy;
                }
                private static void _ModifiedBy_OnValueChanged(global::LightSwitchApplication.tblFeatureRelation e)
                {
                    e.ModifiedBy_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblFeatureRelation, global::LightSwitchApplication.tblFeatureRelation.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry
                    Modified = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblFeatureRelation, global::LightSwitchApplication.tblFeatureRelation.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry(
                        "Modified",
                        global::LightSwitchApplication.tblFeatureRelation.DetailsClass.PropertySetProperties._Modified_Stub,
                        global::LightSwitchApplication.tblFeatureRelation.DetailsClass.PropertySetProperties._Modified_ComputeIsReadOnly,
                        global::LightSwitchApplication.tblFeatureRelation.DetailsClass.PropertySetProperties._Modified_Validate,
                        global::LightSwitchApplication.tblFeatureRelation.DetailsClass.PropertySetProperties._Modified_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.tblFeatureRelation.DetailsClass.PropertySetProperties._Modified_OnValueChanged);
                private static void _Modified_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.tblFeatureRelation.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblFeatureRelation, global::LightSwitchApplication.tblFeatureRelation.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data> c, global::LightSwitchApplication.tblFeatureRelation.DetailsClass d, object sf)
                {
                    c(d, ref d._Modified, sf);
                }
                private static bool _Modified_ComputeIsReadOnly(global::LightSwitchApplication.tblFeatureRelation e)
                {
                    bool result = false;
                    e.Modified_IsReadOnly(ref result);
                    return result;
                }
                private static void _Modified_Validate(global::LightSwitchApplication.tblFeatureRelation e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Modified_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTimeOffset> _Modified_GetImplementationValue(global::LightSwitchApplication.tblFeatureRelation.DetailsClass d)
                {
                    return d.ImplementationEntity.Modified;
                }
                private static void _Modified_OnValueChanged(global::LightSwitchApplication.tblFeatureRelation e)
                {
                    e.Modified_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblFeatureRelation, global::LightSwitchApplication.tblFeatureRelation.DetailsClass, byte[]>.Entry
                    RowVersion = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblFeatureRelation, global::LightSwitchApplication.tblFeatureRelation.DetailsClass, byte[]>.Entry(
                        "RowVersion",
                        global::LightSwitchApplication.tblFeatureRelation.DetailsClass.PropertySetProperties._RowVersion_Stub,
                        global::LightSwitchApplication.tblFeatureRelation.DetailsClass.PropertySetProperties._RowVersion_ComputeIsReadOnly,
                        global::LightSwitchApplication.tblFeatureRelation.DetailsClass.PropertySetProperties._RowVersion_Validate,
                        global::LightSwitchApplication.tblFeatureRelation.DetailsClass.PropertySetProperties._RowVersion_GetImplementationValue,
                        global::LightSwitchApplication.tblFeatureRelation.DetailsClass.PropertySetProperties._RowVersion_SetImplementationValue,
                        global::LightSwitchApplication.tblFeatureRelation.DetailsClass.PropertySetProperties._RowVersion_OnValueChanged);
                private static void _RowVersion_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.tblFeatureRelation.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblFeatureRelation, global::LightSwitchApplication.tblFeatureRelation.DetailsClass, byte[]>.Data> c, global::LightSwitchApplication.tblFeatureRelation.DetailsClass d, object sf)
                {
                    c(d, ref d._RowVersion, sf);
                }
                private static bool _RowVersion_ComputeIsReadOnly(global::LightSwitchApplication.tblFeatureRelation e)
                {
                    bool result = false;
                    e.RowVersion_IsReadOnly(ref result);
                    return result;
                }
                private static void _RowVersion_Validate(global::LightSwitchApplication.tblFeatureRelation e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.RowVersion_Validate(r);
                }
                private static byte[] _RowVersion_GetImplementationValue(global::LightSwitchApplication.tblFeatureRelation.DetailsClass d)
                {
                    return d.ImplementationEntity.RowVersion;
                }
                private static void _RowVersion_SetImplementationValue(global::LightSwitchApplication.tblFeatureRelation.DetailsClass d, byte[] v)
                {
                    d.ImplementationEntity.RowVersion = v;
                }
                private static void _RowVersion_OnValueChanged(global::LightSwitchApplication.tblFeatureRelation e)
                {
                    e.RowVersion_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.tblFeatureRelation, global::LightSwitchApplication.tblFeatureRelation.DetailsClass, global::LightSwitchApplication.tblFeature>.Entry
                    tblFeature = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.tblFeatureRelation, global::LightSwitchApplication.tblFeatureRelation.DetailsClass, global::LightSwitchApplication.tblFeature>.Entry(
                        "tblFeature",
                        global::LightSwitchApplication.tblFeatureRelation.DetailsClass.PropertySetProperties._tblFeature_Stub,
                        global::LightSwitchApplication.tblFeatureRelation.DetailsClass.PropertySetProperties._tblFeature_ComputeIsReadOnly,
                        global::LightSwitchApplication.tblFeatureRelation.DetailsClass.PropertySetProperties._tblFeature_Validate,
                        global::LightSwitchApplication.tblFeatureRelation.DetailsClass.PropertySetProperties._tblFeature_GetCoreImplementationValue,
                        global::LightSwitchApplication.tblFeatureRelation.DetailsClass.PropertySetProperties._tblFeature_GetImplementationValue,
                        global::LightSwitchApplication.tblFeatureRelation.DetailsClass.PropertySetProperties._tblFeature_SetImplementationValue,
                        global::LightSwitchApplication.tblFeatureRelation.DetailsClass.PropertySetProperties._tblFeature_Refresh,
                        global::LightSwitchApplication.tblFeatureRelation.DetailsClass.PropertySetProperties._tblFeature_OnValueChanged);
                private static void _tblFeature_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.tblFeatureRelation.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.tblFeatureRelation, global::LightSwitchApplication.tblFeatureRelation.DetailsClass, global::LightSwitchApplication.tblFeature>.Data> c, global::LightSwitchApplication.tblFeatureRelation.DetailsClass d, object sf)
                {
                    c(d, ref d._tblFeature, sf);
                }
                private static bool _tblFeature_ComputeIsReadOnly(global::LightSwitchApplication.tblFeatureRelation e)
                {
                    bool result = false;
                    e.tblFeature_IsReadOnly(ref result);
                    return result;
                }
                private static void _tblFeature_Validate(global::LightSwitchApplication.tblFeatureRelation e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.tblFeature_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _tblFeature_GetCoreImplementationValue(global::LightSwitchApplication.tblFeatureRelation.DetailsClass d)
                {
                    return d.ImplementationEntity.tblFeature;
                }
                private static global::LightSwitchApplication.tblFeature _tblFeature_GetImplementationValue(global::LightSwitchApplication.tblFeatureRelation.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.tblFeature, global::LightSwitchApplication.tblFeature.DetailsClass>(global::LightSwitchApplication.tblFeatureRelation.DetailsClass.PropertySetProperties.tblFeature, ref d._tblFeature);
                }
                private static void _tblFeature_SetImplementationValue(global::LightSwitchApplication.tblFeatureRelation.DetailsClass d, global::LightSwitchApplication.tblFeature v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.tblFeatureRelation.DetailsClass.PropertySetProperties.tblFeature, ref d._tblFeature, (i, ev) => i.tblFeature = ev, v);
                }
                private static void _tblFeature_Refresh(global::LightSwitchApplication.tblFeatureRelation.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.tblFeatureRelation.DetailsClass.PropertySetProperties.tblFeature, ref d._tblFeature);
                }
                private static void _tblFeature_OnValueChanged(global::LightSwitchApplication.tblFeatureRelation e)
                {
                    e.tblFeature_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.tblFeatureRelation, global::LightSwitchApplication.tblFeatureRelation.DetailsClass, global::LightSwitchApplication.tblComputer>.Entry
                    tblComputer = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.tblFeatureRelation, global::LightSwitchApplication.tblFeatureRelation.DetailsClass, global::LightSwitchApplication.tblComputer>.Entry(
                        "tblComputer",
                        global::LightSwitchApplication.tblFeatureRelation.DetailsClass.PropertySetProperties._tblComputer_Stub,
                        global::LightSwitchApplication.tblFeatureRelation.DetailsClass.PropertySetProperties._tblComputer_ComputeIsReadOnly,
                        global::LightSwitchApplication.tblFeatureRelation.DetailsClass.PropertySetProperties._tblComputer_Validate,
                        global::LightSwitchApplication.tblFeatureRelation.DetailsClass.PropertySetProperties._tblComputer_GetCoreImplementationValue,
                        global::LightSwitchApplication.tblFeatureRelation.DetailsClass.PropertySetProperties._tblComputer_GetImplementationValue,
                        global::LightSwitchApplication.tblFeatureRelation.DetailsClass.PropertySetProperties._tblComputer_SetImplementationValue,
                        global::LightSwitchApplication.tblFeatureRelation.DetailsClass.PropertySetProperties._tblComputer_Refresh,
                        global::LightSwitchApplication.tblFeatureRelation.DetailsClass.PropertySetProperties._tblComputer_OnValueChanged);
                private static void _tblComputer_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.tblFeatureRelation.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.tblFeatureRelation, global::LightSwitchApplication.tblFeatureRelation.DetailsClass, global::LightSwitchApplication.tblComputer>.Data> c, global::LightSwitchApplication.tblFeatureRelation.DetailsClass d, object sf)
                {
                    c(d, ref d._tblComputer, sf);
                }
                private static bool _tblComputer_ComputeIsReadOnly(global::LightSwitchApplication.tblFeatureRelation e)
                {
                    bool result = false;
                    e.tblComputer_IsReadOnly(ref result);
                    return result;
                }
                private static void _tblComputer_Validate(global::LightSwitchApplication.tblFeatureRelation e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.tblComputer_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _tblComputer_GetCoreImplementationValue(global::LightSwitchApplication.tblFeatureRelation.DetailsClass d)
                {
                    return d.ImplementationEntity.tblComputer;
                }
                private static global::LightSwitchApplication.tblComputer _tblComputer_GetImplementationValue(global::LightSwitchApplication.tblFeatureRelation.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.tblComputer, global::LightSwitchApplication.tblComputer.DetailsClass>(global::LightSwitchApplication.tblFeatureRelation.DetailsClass.PropertySetProperties.tblComputer, ref d._tblComputer);
                }
                private static void _tblComputer_SetImplementationValue(global::LightSwitchApplication.tblFeatureRelation.DetailsClass d, global::LightSwitchApplication.tblComputer v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.tblFeatureRelation.DetailsClass.PropertySetProperties.tblComputer, ref d._tblComputer, (i, ev) => i.tblComputer = ev, v);
                }
                private static void _tblComputer_Refresh(global::LightSwitchApplication.tblFeatureRelation.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.tblFeatureRelation.DetailsClass.PropertySetProperties.tblComputer, ref d._tblComputer);
                }
                private static void _tblComputer_OnValueChanged(global::LightSwitchApplication.tblFeatureRelation e)
                {
                    e.tblComputer_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblFeatureRelation, global::LightSwitchApplication.tblFeatureRelation.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblFeatureRelation, global::LightSwitchApplication.tblFeatureRelation.DetailsClass, string>.Data _CreatedBy;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblFeatureRelation, global::LightSwitchApplication.tblFeatureRelation.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data _Created;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblFeatureRelation, global::LightSwitchApplication.tblFeatureRelation.DetailsClass, string>.Data _ModifiedBy;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblFeatureRelation, global::LightSwitchApplication.tblFeatureRelation.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data _Modified;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.tblFeatureRelation, global::LightSwitchApplication.tblFeatureRelation.DetailsClass, byte[]>.Data _RowVersion;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.tblFeatureRelation, global::LightSwitchApplication.tblFeatureRelation.DetailsClass, global::LightSwitchApplication.tblFeature>.Data _tblFeature;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.tblFeatureRelation, global::LightSwitchApplication.tblFeatureRelation.DetailsClass, global::LightSwitchApplication.tblComputer>.Data _tblComputer;
            
        }
    
        #endregion
    }
    
    #endregion
}
