application: medlem3060
version: 1
runtime: python
api_version: 1

handlers:
- url: /_ah/queue/default
  script: main.py
  login: admin

- url: /images
  static_dir: images
  
- url: /stylesheets
  static_dir: stylesheets
  
- url: /w3c
  static_dir: w3c

- url: /adm.*
  script: main.py
  login: required
  
- url: .*
  script: main.py
