application: testmedlem3060
version: 1
runtime: python
api_version: 1

handlers:
- url: /_ah/queue/default
  script: main.py
  login: admin

- url: /images
  static_dir: images
  expiration: "4d 5h"

- url: /software
  static_dir: software
  expiration: "4d 5h"
  
- url: /javascripts
  static_dir: javascripts
  expiration: "1h"
  
- url: /stylesheets
  static_dir: stylesheets
  
- url: /w3c
  static_dir: w3c

- url: /teknik.*
  script: main.py
  login: admin
  
- url: /adm.*
  script: main.py
  login: required
  
- url: .*
  script: main.py
