//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nsPbs3060
{
    using System;
    using System.Collections.Generic;
    
    public partial class ecpwt_user_usergroup_map
    {
        public long user_id { get; set; }
        public long group_id { get; set; }
    }
}
