//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpdateMedlem2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbPuls3060 : DbContext
    {
        public dbPuls3060()
            : base("name=dbPuls3060")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ecpwt_rsmembership_membership_subscribers> ecpwt_rsmembership_membership_subscribers { get; set; }
        public DbSet<ecpwt_rsmembership_transactions> ecpwt_rsmembership_transactions { get; set; }
        public DbSet<ecpwt_rsmembership_transactions_user_data> ecpwt_rsmembership_transactions_user_data { get; set; }
    }
}
