//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpdateMedlem2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ecpwt_rsmembership_transactions_user_data
    {
        public int id { get; set; }
        public string name { get; set; }
        public string adresse { get; set; }
        public string postnr { get; set; }
        public string bynavn { get; set; }
        public string mobil { get; set; }
        public string email { get; set; }
        public string kon { get; set; }
        public string fodtaar { get; set; }
        public string memberid { get; set; }
    }
}
