ALTER TABLE [tblbet] DROP CONSTRAINT [FK_tblfrapbs_tblbet];
ALTER TABLE [tblbetlin] DROP CONSTRAINT [FK_tblbet_tblbetlin];
ALTER TABLE [tblfak] DROP CONSTRAINT [FK_tbltilpbs_tblfak];
ALTER TABLE [tblfrapbs] DROP CONSTRAINT [FK_tblPBSForsendelse_tblfrapbs];
ALTER TABLE [tblMedlemLog] DROP CONSTRAINT [FK_Log_Medlem]; 
ALTER TABLE [tblpbsfile] DROP CONSTRAINT [FK_tblpbsfiles_tblpbsfile];
ALTER TABLE [tblpbsfiles] DROP CONSTRAINT [pbsforsendelse_tblpbsfiles];
ALTER TABLE [tblRegnskab] DROP CONSTRAINT [FK_tblAktivtRegnskab_tblRegnskab];
ALTER TABLE [tbltilpbs] DROP CONSTRAINT [FK_tblPBSForsendelse_tbltilpbs];

DROP TABLE [dicMedlem];
DROP TABLE [syncMedlem];
DROP TABLE [tblAktivitet];
DROP TABLE [tblAktivtRegnskab];
DROP TABLE [tblApplication];
DROP TABLE [tblbet];
DROP TABLE [tblbetlin];
DROP TABLE [tblfak];
DROP TABLE [tblfrapbs];
DROP TABLE [tblkreditor];
DROP TABLE [tblMedlem];
DROP TABLE [tblMedlemLog];
DROP TABLE [tblnrserie];
DROP TABLE [tblpbsfile];
DROP TABLE [tblpbsfiles];
DROP TABLE [tblpbsforsendelse];
DROP TABLE [tblpbsnetdir];
DROP TABLE [tblRegnskab];
DROP TABLE [tblSyncMedlem];
DROP TABLE [tbltilpbs];
DROP TABLE [tempDkkonti];
DROP TABLE [tempFields];
DROP TABLE [tempKartotek];
DROP TABLE [tempKortnr];
DROP TABLE [tempStatus];
DROP TABLE [tblKontingent];
