<%@ Assembly Name="Microsoft.SharePoint, Version=12.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c" %>
<%@ Assembly Name="Kurv, Version=1.0.0.0, Culture=neutral, PublicKeyToken=9f4da00116c38ec5" %>
<%@ Assembly Name="spListDB, Version=1.0.0.0, Culture=neutral, PublicKeyToken=9f4da00116c38ec5" %>

<%@ Register TagPrefix="SharePoint" Namespace="Microsoft.SharePoint.WebControls"
    Assembly="Microsoft.SharePoint, Version=12.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c" %>

<%@ Register Assembly="RadGrid.Net2, Version=5.1.0.0, Culture=neutral, PublicKeyToken=ec87bc2939ec45df"
    Namespace="Telerik.WebControls" TagPrefix="rad" %>

<%@ Page Language="C#" MasterPageFile="~/_layouts/application.master" Inherits="CustomApplicationPages.Kurv"
    EnableViewState="true" EnableViewStateMac="true" %>

<%@ Import Namespace="spListDB"  %>

<script runat="server">

    protected void ObjectDataSource1_ObjectCreating(object sender, ObjectDataSourceEventArgs e)
    {

    }
</script>

<asp:Content ID="Main" ContentPlaceHolderID="PlaceHolderMain" runat="server">
    <table border="1" cellpadding="4" cellspacing="0" style="font-size: 12">
        <tr>
            <td>
                Site Title:</td>
            <td>
                <asp:Label ID="lblSiteTitle" runat="server" /></td>
        </tr>
        <tr>
            <td>
                Site ID:</td>
            <td>
                <asp:Label ID="lblSiteID" runat="server" /></td>
        </tr>
    </table>
    &nbsp;<br />
    &nbsp;&nbsp;
    <br />
    <SharePoint:SPDataSource ID="spdatasource1" runat="server" DataSourceMode="List"
        SelectCommand='<View><ViewFields><FieldRef Name="ID"/><FieldRef Name="Title"/><FieldRef Name="PermMask"/></ViewFields></View>'
        UseInternalName="true" Scope="Recursive" OnSelecting="spdatasource1_Selecting">
        <SelectParameters>
            <asp:Parameter DefaultValue="DF806E7E-0073-4202-99E3-C4A269E2FA5D" Name="ListID" />
        </SelectParameters>
        <DeleteParameters>
            <asp:Parameter DefaultValue="DF806E7E-0073-4202-99E3-C4A269E2FA5D" Name="ListID" />
        </DeleteParameters>
        <UpdateParameters>
            <asp:PARAMETER DefaultValue="DF806E7E-0073-4202-99E3-C4A269E2FA5D" Name="ListID" />
        </UpdateParameters>
        <InsertParameters>
            <asp:PARAMETER DefaultValue="DF806E7E-0073-4202-99E3-C4A269E2FA5D" Name="ListID" />
        </InsertParameters>
    </SharePoint:SPDataSource>
    <rad:RadGrid ID="RadGrid1" runat="server" DataSourceID="spdatasource1" GridLines="None"
        Skin="WebBlue" RadControlsDir="/_wpresources/RadGrid.Net2/5.1.0.0__ec87bc2939ec45df/RadControls/"
        AutoGenerateDeleteColumn="True" AutoGenerateEditColumn="True" SkinsPath="/_wpresources/RadGrid.Net2/5.1.0.0__ec87bc2939ec45df/RadControls/Grid/Skins"
        EnableAJAX="True" AutoGenerateColumns="False"
        Width="540px" OnDataBinding="RadGrid1_DataBinding">
        <MasterTableView DataKeyNames="ID" DataSourceID="spdatasource1" AllowAutomaticInserts="True"
            AllowAutomaticUpdates="True" AllowCustomPaging="True" AllowCustomSorting="True">
            <RowIndicatorColumn Visible="False">
                <HeaderStyle Width="20px" />
            </RowIndicatorColumn>
            <ExpandCollapseColumn Resizable="False" Visible="False">
                <HeaderStyle Width="20px" />
            </ExpandCollapseColumn>
            <Columns>
                <rad:GridEditCommandColumn UniqueName="AutoGeneratedEditColumn">
                    <HeaderStyle Width="30px" />
                </rad:GridEditCommandColumn>
                <rad:GridButtonColumn CommandName="Delete" Text="Delete" UniqueName="AutoGeneratedDeleteColumn">
                    <HeaderStyle Width="45px" />
                </rad:GridButtonColumn>
                <rad:GridBoundColumn DataField="Title" HeaderText="Titel" UniqueName="column">
                </rad:GridBoundColumn>
            </Columns>
        </MasterTableView>
    </rad:RadGrid>
    <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" DataSourceID="ObjectDataSource1" OnDataBinding="GridView1_DataBinding">
        <Columns>
            <asp:BoundField DataField="ID" HeaderText="ID" />
            <asp:BoundField DataField="Title" HeaderText="Title" />
        </Columns>
    </asp:GridView>
    <asp:ObjectDataSource ID="ObjectDataSource1" runat="server" TypeName="spListDB.spListDB" SelectMethod="GetLists" OnSelecting="ObjectDataSource1_Selecting" OnObjectCreating="ObjectDataSource1_ObjectCreating" ></asp:ObjectDataSource>
</asp:Content>
<asp:Content ID="PageTitle" runat="server" ContentPlaceHolderID="PlaceHolderPageTitle">
    Hello World
</asp:Content>
<asp:Content ID="PageTitleInTitleArea" runat="server" ContentPlaceHolderID="PlaceHolderPageTitleInTitleArea">
    Application Page 1: 'Hello World' with code behind
</asp:Content>
