//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nsPbs3060v2
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAktivitet
    {
        public tblAktivitet()
        {
            this.tblMedlemLog = new HashSet<tblMedlemLog>();
        }
    
        public int id { get; set; }
        public string akt_tekst { get; set; }
    
        public virtual ICollection<tblMedlemLog> tblMedlemLog { get; set; }
    }
}
