#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.276
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nsMedlem3060Service
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="puls3061_dk_db")]
	public partial class dbJobQDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserttblJobqueue(tblJobqueue instance);
    partial void UpdatetblJobqueue(tblJobqueue instance);
    partial void DeletetblJobqueue(tblJobqueue instance);
    partial void InserttblSchedule(tblSchedule instance);
    partial void UpdatetblSchedule(tblSchedule instance);
    partial void DeletetblSchedule(tblSchedule instance);
    #endregion
		
		public dbJobQDataContext() : 
				base(global::nsMedlem3060Service.Properties.Settings.Default.puls3061_dk_dbConnectionString_Test, mappingSource)
		{
			OnCreated();
		}
		
		public dbJobQDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbJobQDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbJobQDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbJobQDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tblJobqueue> tblJobqueues
		{
			get
			{
				return this.GetTable<tblJobqueue>();
			}
		}
		
		public System.Data.Linq.Table<tblSchedule> tblSchedules
		{
			get
			{
				return this.GetTable<tblSchedule>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.jobqueueadd")]
		public int jobqueueadd([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> starttime, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(25)")] string jobname, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> scheduleid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> onhold)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), starttime, jobname, scheduleid, onhold);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.jobqueuecomplete")]
		public int jobqueuecomplete([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.jobqueuenext")]
		public int jobqueuenext([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(25)")] ref string jobname)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, jobname);
			id = ((System.Nullable<int>)(result.GetParameterValue(0)));
			jobname = ((string)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblJobqueue")]
	public partial class tblJobqueue : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _scheduleid;
		
		private System.DateTime _starttime;
		
		private string _jobname;
		
		private System.Nullable<bool> _onhold;
		
		private System.Nullable<bool> _selected;
		
		private System.Nullable<bool> _completed;
		
		private EntityRef<tblSchedule> _tblSchedule;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnscheduleidChanging(System.Nullable<int> value);
    partial void OnscheduleidChanged();
    partial void OnstarttimeChanging(System.DateTime value);
    partial void OnstarttimeChanged();
    partial void OnjobnameChanging(string value);
    partial void OnjobnameChanged();
    partial void OnonholdChanging(System.Nullable<bool> value);
    partial void OnonholdChanged();
    partial void OnselectedChanging(System.Nullable<bool> value);
    partial void OnselectedChanged();
    partial void OncompletedChanging(System.Nullable<bool> value);
    partial void OncompletedChanged();
    #endregion
		
		public tblJobqueue()
		{
			this._tblSchedule = default(EntityRef<tblSchedule>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_scheduleid", DbType="Int")]
		public System.Nullable<int> scheduleid
		{
			get
			{
				return this._scheduleid;
			}
			set
			{
				if ((this._scheduleid != value))
				{
					if (this._tblSchedule.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnscheduleidChanging(value);
					this.SendPropertyChanging();
					this._scheduleid = value;
					this.SendPropertyChanged("scheduleid");
					this.OnscheduleidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_starttime", DbType="DateTime NOT NULL")]
		public System.DateTime starttime
		{
			get
			{
				return this._starttime;
			}
			set
			{
				if ((this._starttime != value))
				{
					this.OnstarttimeChanging(value);
					this.SendPropertyChanging();
					this._starttime = value;
					this.SendPropertyChanged("starttime");
					this.OnstarttimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jobname", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
		public string jobname
		{
			get
			{
				return this._jobname;
			}
			set
			{
				if ((this._jobname != value))
				{
					this.OnjobnameChanging(value);
					this.SendPropertyChanging();
					this._jobname = value;
					this.SendPropertyChanged("jobname");
					this.OnjobnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_onhold", DbType="Bit")]
		public System.Nullable<bool> onhold
		{
			get
			{
				return this._onhold;
			}
			set
			{
				if ((this._onhold != value))
				{
					this.OnonholdChanging(value);
					this.SendPropertyChanging();
					this._onhold = value;
					this.SendPropertyChanged("onhold");
					this.OnonholdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_selected", DbType="Bit")]
		public System.Nullable<bool> selected
		{
			get
			{
				return this._selected;
			}
			set
			{
				if ((this._selected != value))
				{
					this.OnselectedChanging(value);
					this.SendPropertyChanging();
					this._selected = value;
					this.SendPropertyChanged("selected");
					this.OnselectedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_completed", DbType="Bit")]
		public System.Nullable<bool> completed
		{
			get
			{
				return this._completed;
			}
			set
			{
				if ((this._completed != value))
				{
					this.OncompletedChanging(value);
					this.SendPropertyChanging();
					this._completed = value;
					this.SendPropertyChanged("completed");
					this.OncompletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblSchedule_tblJobqueue", Storage="_tblSchedule", ThisKey="scheduleid", OtherKey="id", IsForeignKey=true, DeleteRule="SET NULL")]
		public tblSchedule tblSchedule
		{
			get
			{
				return this._tblSchedule.Entity;
			}
			set
			{
				tblSchedule previousValue = this._tblSchedule.Entity;
				if (((previousValue != value) 
							|| (this._tblSchedule.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblSchedule.Entity = null;
						previousValue.tblJobqueues.Remove(this);
					}
					this._tblSchedule.Entity = value;
					if ((value != null))
					{
						value.tblJobqueues.Add(this);
						this._scheduleid = value.id;
					}
					else
					{
						this._scheduleid = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblSchedule");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblSchedule")]
	public partial class tblSchedule : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _schedule;
		
		private string _jobname;
		
		private System.Nullable<System.DateTime> _start;
		
		private System.Nullable<System.DateTime> _end;
		
		private EntitySet<tblJobqueue> _tblJobqueues;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnscheduleChanging(string value);
    partial void OnscheduleChanged();
    partial void OnjobnameChanging(string value);
    partial void OnjobnameChanged();
    partial void OnstartChanging(System.Nullable<System.DateTime> value);
    partial void OnstartChanged();
    partial void OnendChanging(System.Nullable<System.DateTime> value);
    partial void OnendChanged();
    #endregion
		
		public tblSchedule()
		{
			this._tblJobqueues = new EntitySet<tblJobqueue>(new Action<tblJobqueue>(this.attach_tblJobqueues), new Action<tblJobqueue>(this.detach_tblJobqueues));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_schedule", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
		public string schedule
		{
			get
			{
				return this._schedule;
			}
			set
			{
				if ((this._schedule != value))
				{
					this.OnscheduleChanging(value);
					this.SendPropertyChanging();
					this._schedule = value;
					this.SendPropertyChanged("schedule");
					this.OnscheduleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jobname", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
		public string jobname
		{
			get
			{
				return this._jobname;
			}
			set
			{
				if ((this._jobname != value))
				{
					this.OnjobnameChanging(value);
					this.SendPropertyChanging();
					this._jobname = value;
					this.SendPropertyChanged("jobname");
					this.OnjobnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_start", DbType="Date")]
		public System.Nullable<System.DateTime> start
		{
			get
			{
				return this._start;
			}
			set
			{
				if ((this._start != value))
				{
					this.OnstartChanging(value);
					this.SendPropertyChanging();
					this._start = value;
					this.SendPropertyChanged("start");
					this.OnstartChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[end]", Storage="_end", DbType="Date")]
		public System.Nullable<System.DateTime> end
		{
			get
			{
				return this._end;
			}
			set
			{
				if ((this._end != value))
				{
					this.OnendChanging(value);
					this.SendPropertyChanging();
					this._end = value;
					this.SendPropertyChanged("end");
					this.OnendChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblSchedule_tblJobqueue", Storage="_tblJobqueues", ThisKey="id", OtherKey="scheduleid")]
		public EntitySet<tblJobqueue> tblJobqueues
		{
			get
			{
				return this._tblJobqueues;
			}
			set
			{
				this._tblJobqueues.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblJobqueues(tblJobqueue entity)
		{
			this.SendPropertyChanging();
			entity.tblSchedule = this;
		}
		
		private void detach_tblJobqueues(tblJobqueue entity)
		{
			this.SendPropertyChanging();
			entity.tblSchedule = null;
		}
	}
}
#pragma warning restore 1591
